#!/usr/bin/env python3
"""Rehearse a synthetic release-object round trip against S3-compatible storage.

The command is deliberately dry-run by default.  An actual object write needs
both ``--execute`` and an exact ``--confirm-bucket`` value, and production also
needs ``--allow-production``.  The payload is generated by this script; no
customer document or release artifact path is accepted.  The object is removed
after verification, so a passing rehearsal leaves no object behind.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
import uuid
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.config import settings  # noqa: E402
from app.storage import S3CompatibleStorage, StorageError, get_storage  # noqa: E402


SYNTHETIC_PAYLOAD = (
    b"NITE DSP synthetic release-storage rehearsal\n"
    b"format=v1\n"
    b"contains_customer_documents=false\n"
)


def _rehearsal_key() -> str:
    return f"rehearsals/nite-submit/storage-round-trip/{uuid.uuid4().hex}.bin"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Verify synthetic S3-compatible release storage and clean up the probe."
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="perform the guarded object write/read/checksum/delete rehearsal",
    )
    parser.add_argument(
        "--confirm-bucket",
        help="exact configured bucket name; required with --execute",
    )
    parser.add_argument(
        "--allow-production",
        action="store_true",
        help="allow execution when ENVIRONMENT=production (still requires --confirm-bucket)",
    )
    return parser


def _dry_run() -> int:
    print(
        json.dumps(
            {
                "status": "dry-run",
                "environment": settings.environment,
                "storage_backend": settings.storage_backend,
                "planned_prefix": "rehearsals/nite-submit/storage-round-trip/",
                "payload_bytes": len(SYNTHETIC_PAYLOAD),
                "writes_attempted": False,
                "customer_documents_accepted": False,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def _execute(confirm_bucket: str | None, allow_production: bool) -> int:
    if not confirm_bucket:
        print("--confirm-bucket is required with --execute; no write attempted", file=sys.stderr)
        return 2
    if settings.environment not in {"staging", "production"}:
        print("execution is limited to an explicit staging or production environment", file=sys.stderr)
        return 2
    if settings.environment == "production" and not allow_production:
        print("production execution requires --allow-production; no write attempted", file=sys.stderr)
        return 2
    if settings.storage_backend.strip().lower() != "s3":
        print("storage_backend must be 's3' for execution; no write attempted", file=sys.stderr)
        return 2
    if confirm_bucket != settings.storage_bucket:
        print("--confirm-bucket does not match the configured bucket; no write attempted", file=sys.stderr)
        return 2

    storage = get_storage()
    if not isinstance(storage, S3CompatibleStorage):
        print("configured storage is not the S3-compatible adapter; no write attempted", file=sys.stderr)
        return 2

    key = _rehearsal_key()
    checksum = hashlib.sha256(SYNTHETIC_PAYLOAD).hexdigest()
    uploaded = False
    try:
        with tempfile.NamedTemporaryFile(prefix="nite-dsp-storage-rehearsal-", suffix=".bin") as source:
            source.write(SYNTHETIC_PAYLOAD)
            source.flush()
            storage.put_file(Path(source.name), key, checksum)
        uploaded = True
        if not storage.exists(key):
            raise StorageError("rehearsal object was not found after upload")
        if storage.sha256(key) != checksum:
            raise StorageError("rehearsal object checksum did not round-trip")
        storage.delete_rehearsal_object(key)
        uploaded = False
        if storage.exists(key):
            raise StorageError("rehearsal object remained after cleanup")
    except Exception as exc:  # noqa: BLE001 - provider SDK errors vary by S3-compatible service
        if uploaded:
            try:
                storage.delete_rehearsal_object(key)
            except Exception:  # noqa: BLE001 - preserve the original operator failure
                pass
        print(f"S3 storage rehearsal failed: {exc}", file=sys.stderr)
        return 1

    print(
        json.dumps(
            {
                "status": "pass",
                "environment": settings.environment,
                "storage_backend": "s3",
                "key_prefix": "rehearsals/nite-submit/storage-round-trip/",
                "payload_bytes": len(SYNTHETIC_PAYLOAD),
                "checksum_sha256": checksum,
                "cleaned_up": True,
                "customer_documents_accepted": False,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.execute:
        return _dry_run()
    return _execute(args.confirm_bucket, args.allow_production)


if __name__ == "__main__":
    raise SystemExit(main())
