import Foundation

/// Type of organization rule applied to a library folder.
public enum OrganizationRuleType: Codable, Equatable, Sendable {
    case groupByCategory
    case datePrefix
    case customTemplate(template: String)

    public var displayName: String {
        switch self {
        case .groupByCategory: return "Group by File Category"
        case .datePrefix: return "Date Prefix (YYYY-MM-DD)"
        case .customTemplate(let template): return "Custom Template (\(template))"
        }
    }
}

/// A proposed file relocation action generated by the OrganizationRulesEngine.
public struct ProposedFileAction: Codable, Equatable, Sendable {
    public enum ActionType: String, Codable, Sendable {
        case move
        case copy
        case rename
    }

    public var sourceURL: URL
    public var destinationURL: URL
    public var actionType: ActionType
    public var reason: String
    public var hasCollision: Bool

    public init(sourceURL: URL, destinationURL: URL, actionType: ActionType, reason: String, hasCollision: Bool) {
        self.sourceURL = sourceURL
        self.destinationURL = destinationURL
        self.actionType = actionType
        self.reason = reason
        self.hasCollision = hasCollision
    }
}

/// The complete organization plan generated for a scanned folder.
public struct OrganizationPlan: Codable, Equatable, Sendable {
    public var targetDirectory: URL
    public var ruleType: OrganizationRuleType
    public var actions: [ProposedFileAction]
    public var totalFilesToProcess: Int
    public var collisionsCount: Int

    public init(targetDirectory: URL, ruleType: OrganizationRuleType, actions: [ProposedFileAction]) {
        self.targetDirectory = targetDirectory
        self.ruleType = ruleType
        self.actions = actions
        self.totalFilesToProcess = actions.count
        self.collisionsCount = actions.filter(\.hasCollision).count
    }
}

/// Engine that processes a ScannedFolderManifest and produces an OrganizationPlan.
public struct OrganizationRulesEngine: Sendable {
    public init() {}

    public func generatePlan(
        manifest: ScannedFolderManifest,
        ruleType: OrganizationRuleType,
        destinationDirectory: URL? = nil,
        copyMode: Bool = true
    ) -> OrganizationPlan {
        let baseDir = destinationDirectory ?? manifest.rootURL
        var proposedActions: [ProposedFileAction] = []
        var existingDestinations: Set<String> = []

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        dateFormatter.locale = Locale(identifier: "en_US_POSIX")

        for file in manifest.files {
            let srcURL = file.url
            let originalName = srcURL.lastPathComponent
            let ext = file.extensionName
            var relativeDestPath = ""

            switch ruleType {
            case .groupByCategory:
                let categoryFolder = file.category.folderName
                relativeDestPath = "\(categoryFolder)/\(originalName)"

            case .datePrefix:
                let dateStr: String
                if let modDate = file.modifiedDate {
                    dateStr = dateFormatter.string(from: modDate)
                } else if let createDate = file.createdDate {
                    dateStr = dateFormatter.string(from: createDate)
                } else {
                    dateStr = "unknown-date"
                }

                if originalName.hasPrefix(dateStr) {
                    relativeDestPath = originalName
                } else {
                    relativeDestPath = "\(dateStr)_\(originalName)"
                }

            case .customTemplate(let tmpl):
                var subPath = tmpl
                subPath = subPath.replacingOccurrences(of: "{category}", with: file.category.folderName)
                subPath = subPath.replacingOccurrences(of: "{extension}", with: ext.isEmpty ? "no_ext" : ext.lowercased())
                subPath = subPath.replacingOccurrences(of: "{filename}", with: originalName)

                let dateStr = (file.modifiedDate != nil) ? dateFormatter.string(from: file.modifiedDate!) : "unknown-date"
                subPath = subPath.replacingOccurrences(of: "{date}", with: dateStr)

                relativeDestPath = subPath
            }

            let destURL = baseDir.appendingPathComponent(relativeDestPath)
            let destPathString = destURL.path

            let fm = FileManager.default
            let existsOnDisk = fm.fileExists(atPath: destPathString) && destPathString != srcURL.path
            let isDuplicateInBatch = existingDestinations.contains(destPathString)
            let hasCollision = existsOnDisk || isDuplicateInBatch

            existingDestinations.insert(destPathString)

            let actionType: ProposedFileAction.ActionType = copyMode ? .copy : .move
            let reason = "Rule: \(ruleType.displayName) -> \(relativeDestPath)"

            let action = ProposedFileAction(
                sourceURL: srcURL,
                destinationURL: destURL,
                actionType: actionType,
                reason: reason,
                hasCollision: hasCollision
            )
            proposedActions.append(action)
        }

        return OrganizationPlan(
            targetDirectory: baseDir,
            ruleType: ruleType,
            actions: proposedActions
        )
    }
}
