import Foundation

/// Type of organization rule applied to a library folder.
public enum OrganizationRuleType: Codable, Equatable, Sendable {
    case groupByCategory
    case datePrefix
    case customTemplate(template: String)

    public var displayName: String {
        switch self {
        case .groupByCategory: return "Group by File Category"
        case .datePrefix: return "Date Prefix (YYYY-MM-DD)"
        case .customTemplate(let template): return "Custom Template (\(template))"
        }
    }
}

/// A proposed file relocation action generated by the OrganizationRulesEngine.
public struct ProposedFileAction: Codable, Equatable, Sendable {
    public enum ActionType: String, Codable, Sendable {
        case move
        case copy
        case rename
    }

    public var sourceURL: URL
    public var destinationURL: URL
    public var actionType: ActionType
    public var reason: String
    public var hasCollision: Bool

    public init(sourceURL: URL, destinationURL: URL, actionType: ActionType, reason: String, hasCollision: Bool) {
        self.sourceURL = sourceURL
        self.destinationURL = destinationURL
        self.actionType = actionType
        self.reason = reason
        self.hasCollision = hasCollision
    }
}

/// The complete organization plan generated for a scanned folder.
public struct OrganizationPlan: Codable, Equatable, Sendable {
    public var targetDirectory: URL
    public var ruleType: OrganizationRuleType
    public var actions: [ProposedFileAction]
    public var totalFilesToProcess: Int
    public var collisionsCount: Int

    public init(targetDirectory: URL, ruleType: OrganizationRuleType, actions: [ProposedFileAction]) {
        self.targetDirectory = targetDirectory
        self.ruleType = ruleType
        self.actions = actions
        self.totalFilesToProcess = actions.count
        self.collisionsCount = actions.filter(\.hasCollision).count
    }
}

/// Engine that processes a ScannedFolderManifest and produces an OrganizationPlan.
public struct OrganizationRulesEngine: Sendable {
    public init() {}

    public func generatePlan(
        manifest: ScannedFolderManifest,
        ruleType: OrganizationRuleType,
        destinationDirectory: URL? = nil,
        copyMode: Bool = true
    ) -> OrganizationPlan {
        let baseDir = destinationDirectory ?? manifest.rootURL
        var proposedActions: [ProposedFileAction] = []
        var existingDestinations: Set<String> = []

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        dateFormatter.locale = Locale(identifier: "en_US_POSIX")

        for file in manifest.files {
            let srcURL = file.url
            let originalName = srcURL.lastPathComponent
            let ext = file.extensionName
            // We sanitise here because lastPathComponent can still carry
            // dots, spaces, or reserved device names, and the custom template
            // below interpolates it verbatim into a relative path.
            let safeFilename = FilenameSanitizer.sanitize(originalName)
            let safeExt = ext.isEmpty ? "no_ext" : FilenameSanitizer.sanitize(ext.lowercased())
            let safeCategory = FilenameSanitizer.sanitize(file.category.folderName)
            var relativeDestPath = ""
            var traversalBlocked = false

            switch ruleType {
            case .groupByCategory:
                relativeDestPath = "\(safeCategory)/\(safeFilename)"

            case .datePrefix:
                let dateStr: String
                if let modDate = file.modifiedDate {
                    dateStr = dateFormatter.string(from: modDate)
                } else if let createDate = file.createdDate {
                    dateStr = dateFormatter.string(from: createDate)
                } else {
                    dateStr = "unknown-date"
                }

                if safeFilename.hasPrefix(dateStr) {
                    relativeDestPath = safeFilename
                } else {
                    relativeDestPath = "\(dateStr)_\(safeFilename)"
                }

            case .customTemplate(let tmpl):
                var subPath = tmpl
                subPath = subPath.replacingOccurrences(of: "{category}", with: safeCategory)
                subPath = subPath.replacingOccurrences(of: "{extension}", with: safeExt)
                subPath = subPath.replacingOccurrences(of: "{filename}", with: safeFilename)

                let dateStr = (file.modifiedDate != nil) ? dateFormatter.string(from: file.modifiedDate!) : "unknown-date"
                subPath = subPath.replacingOccurrences(of: "{date}", with: dateStr)

                let confined = Self.confinedRelativePath(from: subPath, fallbackName: safeFilename)
                relativeDestPath = confined.path
                traversalBlocked = confined.traversalBlocked
            }

            var destURL = baseDir.appendingPathComponent(relativeDestPath)
            // Belt and braces: a hostile template such as "../../x" must
            // never resolve outside the chosen base directory. Standardise
            // and fall back to the flat sanitised name when it does.
            let baseStandard = baseDir.standardizedFileURL.path
            let destStandard = destURL.standardized.path
            if destStandard != baseStandard && !destStandard.hasPrefix(baseStandard + "/") {
                destURL = baseDir.appendingPathComponent(safeFilename)
                relativeDestPath = safeFilename
                traversalBlocked = true
            }
            let destPathString = destURL.path

            let fm = FileManager.default
            let existsOnDisk = fm.fileExists(atPath: destPathString) && destPathString != srcURL.path
            let isDuplicateInBatch = existingDestinations.contains(destPathString)
            // A blocked traversal is surfaced as a collision so the executor
            // refuses it without force, exactly like an existing file.
            let hasCollision = existsOnDisk || isDuplicateInBatch || traversalBlocked

            existingDestinations.insert(destPathString)

            let actionType: ProposedFileAction.ActionType = copyMode ? .copy : .move
            let reason: String
            if traversalBlocked {
                reason = "Rule: \(ruleType.displayName) -> \(relativeDestPath) (blocked path traversal, confined to base directory)"
            } else {
                reason = "Rule: \(ruleType.displayName) -> \(relativeDestPath)"
            }

            let action = ProposedFileAction(
                sourceURL: srcURL,
                destinationURL: destURL,
                actionType: actionType,
                reason: reason,
                hasCollision: hasCollision
            )
            proposedActions.append(action)
        }

        return OrganizationPlan(
            targetDirectory: baseDir,
            ruleType: ruleType,
            actions: proposedActions
        )
    }

    /// Split a rendered template into path components, sanitise each one,
    /// and reject ".." or absolute segments so the result cannot escape
    /// the base directory. Returns a fallback flat name when traversal
    /// was attempted.
    static func confinedRelativePath(from subPath: String, fallbackName: String) -> (path: String, traversalBlocked: Bool) {
        var cleaned = subPath.replacingOccurrences(of: "\\", with: "/")
        while cleaned.hasPrefix("/") { cleaned.removeFirst() }
        let rawParts = cleaned.split(separator: "/", omittingEmptySubsequences: true).map(String.init)
        if rawParts.isEmpty { return (fallbackName, true) }
        var safeParts: [String] = []
        var blocked = false
        for part in rawParts {
            if part == ".." || part == "." || part.contains("..") {
                blocked = true
                continue
            }
            let safe = FilenameSanitizer.sanitize(part)
            if safe == "Untitled" && part.trimmingCharacters(in: .whitespaces) != "Untitled" {
                // Sanitiser emptied a hostile component such as ".." hidden
                // behind punctuation; drop it rather than inventing folders.
                if part.allSatisfy({ ". _-".contains($0) }) { blocked = true; continue }
            }
            safeParts.append(safe)
        }
        if blocked || safeParts.isEmpty {
            return (fallbackName, true)
        }
        return (safeParts.joined(separator: "/"), false)
    }
}
