"use client";

import { useState } from "react";
import { DemoShell } from "@/components/demo/DemoShell";

type SampleNode = {
  id: string;
  name: string;
  category: string;
  x: number; // 0..100 percentage
  y: number; // 0..100 percentage
  frequency: string;
  centroid: string;
  similarCount: number;
};

const SAMPLE_NODES: SampleNode[] = [
  { id: "1", name: "Analog_Kick_808.wav", category: "Kick", x: 22, y: 78, frequency: "54.2 Hz", centroid: "120 Hz", similarCount: 14 },
  { id: "2", name: "Sub_Drop_Clean.wav", category: "Kick", x: 18, y: 84, frequency: "42.0 Hz", centroid: "95 Hz", similarCount: 9 },
  { id: "3", name: "Snare_Tight_707.wav", category: "Snare", x: 74, y: 35, frequency: "240.5 Hz", centroid: "2.4 kHz", similarCount: 18 },
  { id: "4", name: "Clap_Layer_Wide.wav", category: "Snare", x: 82, y: 28, frequency: "310.0 Hz", centroid: "3.1 kHz", similarCount: 12 },
  { id: "5", name: "Hat_Closed_Crisp.wav", category: "Hi-Hat", x: 88, y: 75, frequency: "8.4 kHz", centroid: "10.2 kHz", similarCount: 22 },
  { id: "6", name: "Hat_Open_Bright.wav", category: "Hi-Hat", x: 92, y: 82, frequency: "7.8 kHz", centroid: "9.5 kHz", similarCount: 15 },
  { id: "7", name: "FM_Bass_Stab.wav", category: "Synth", x: 38, y: 52, frequency: "110.0 Hz", centroid: "850 Hz", similarCount: 11 },
  { id: "8", name: "Pluck_Warm_C3.wav", category: "Synth", x: 45, y: 40, frequency: "261.6 Hz", centroid: "1.2 kHz", similarCount: 16 },
  { id: "9", name: "Vocal_Chop_Air.wav", category: "FX", x: 62, y: 65, frequency: "440.0 Hz", centroid: "4.5 kHz", similarCount: 8 },
];

export function SloMapDemo() {
  const [selectedNode, setSelectedNode] = useState<SampleNode>(SAMPLE_NODES[0]);
  const [scanning, setScanning] = useState(false);

  function simulateScan() {
    setScanning(true);
    setTimeout(() => {
      setScanning(false);
    }, 1200);
  }

  return (
    <DemoShell
      label="simulation"
      title="SLO // ACOUSTIC SIMILARITY MAP"
      phase={scanning ? "scanning" : "result"}
      onReset={() => setSelectedNode(SAMPLE_NODES[0])}
      ariaLabel="SLO sample map demonstration"
      footerNote="Interactive simulation, 2D acoustic coordinate map generated by local timbral feature extraction."
    >
      <div className="p-5 sm:p-6 bg-surface flex flex-col gap-5">
        {/* Header Control Bar */}
        <div className="flex items-center justify-between gap-3 flex-wrap border-b border-border/50 pb-3">
          <div>
            <span className="text-[11px] font-mono font-bold text-foreground block">
              2D ACOUSTIC SPACE PREVIEW
            </span>
            <span className="text-[10px] font-mono text-muted-dim block mt-0.5">
              964 SAMPLES INDEXED · 100% OFFLINE
            </span>
          </div>

          <button
            type="button"
            onClick={simulateScan}
            disabled={scanning}
            className="px-3 py-1.5 rounded text-xs font-mono font-bold bg-[#F0A23A] text-[#030509] hover:bg-[#FFC94D] transition-all shadow-[0_0_12px_rgba(240,162,58,0.3)] disabled:opacity-50"
          >
            {scanning ? "RE-INDEXING…" : "FIND SIMILAR SAMPLES"}
          </button>
        </div>

        {/* 2D Coordinate Map Container */}
        <div className="relative w-full h-56 rounded-lg dsp-lcd-box overflow-hidden border border-border-strong/60 p-4">
          {/* Subtle grid lines */}
          <div
            className="absolute inset-0 pointer-events-none opacity-20"
            style={{
              backgroundImage: "radial-gradient(#F0A23A 1px, transparent 1px)",
              backgroundSize: "24px 24px",
            }}
          />

          {/* Sample Map Nodes */}
          {SAMPLE_NODES.map((node) => {
            const isSelected = selectedNode.id === node.id;
            return (
              <button
                key={node.id}
                type="button"
                onClick={() => setSelectedNode(node)}
                aria-label={`Select sample ${node.name}`}
                className="absolute transform -translate-x-1/2 -translate-y-1/2 group focus:outline-none"
                style={{ left: `${node.x}%`, top: `${node.y}%` }}
              >
                {/* Halo for selected node */}
                {isSelected && (
                  <span className="absolute inset-0 rounded-full animate-ping bg-[#F0A23A]/40 w-6 h-6 -left-1.5 -top-1.5" />
                )}
                
                {/* Node Dot */}
                <span
                  className={`block rounded-full transition-all ${
                    isSelected
                      ? "w-3.5 h-3.5 bg-[#FFC94D] shadow-[0_0_12px_#F0A23A] ring-2 ring-[#F0A23A]"
                      : "w-2.5 h-2.5 bg-[#F0A23A]/60 group-hover:bg-[#F0A23A] group-hover:scale-125"
                  }`}
                />

                {/* Hover Label */}
                <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1 hidden group-hover:block whitespace-nowrap bg-[#0A0F1D] border border-border text-[9px] font-mono px-2 py-0.5 rounded text-foreground z-10">
                  {node.name}
                </span>
              </button>
            );
          })}
        </div>

        {/* Selected Sample Inspection Rack */}
        <div className="dsp-rack-panel p-4 rounded-lg flex flex-col gap-3">
          <div className="flex items-center justify-between gap-2 border-b border-border/40 pb-2">
            <div className="flex items-center gap-2">
              <span className="dsp-led dsp-led--live" />
              <span className="text-xs font-mono font-bold text-foreground">
                {selectedNode.name}
              </span>
            </div>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-surface-raised border border-border/40 text-[#F0A23A] font-bold">
              {selectedNode.category.toUpperCase()}
            </span>
          </div>

          <div className="grid grid-cols-3 gap-3 text-xs font-mono">
            <div className="p-2 dsp-lcd-box rounded">
              <span className="text-[9px] text-muted-dim block uppercase">PITCH / FUNDAMENTAL</span>
              <span className="text-foreground font-bold tnum block mt-0.5">{selectedNode.frequency}</span>
            </div>
            <div className="p-2 dsp-lcd-box rounded">
              <span className="text-[9px] text-muted-dim block uppercase">SPECTRAL CENTROID</span>
              <span className="text-foreground font-bold tnum block mt-0.5">{selectedNode.centroid}</span>
            </div>
            <div className="p-2 dsp-lcd-box rounded">
              <span className="text-[9px] text-muted-dim block uppercase">SIMILAR NEIGHBORS</span>
              <span className="text-brand-emerald font-bold tnum block mt-0.5">{selectedNode.similarCount} matches</span>
            </div>
          </div>
        </div>

        <p className="text-[11px] font-mono text-muted-dim leading-relaxed">
          SLO organizes your sample library by acoustic timbral characteristics. Drag and drop samples directly into your DAW with zero metadata dependency.
        </p>
      </div>
    </DemoShell>
  );
}
