from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, List, Optional

from audiogen_core.arrangement_config import ArrangementConfiguration
from audiogen_core.composition_config_groups import CompositionRuntimeProfile, build_composition_runtime_profile

if TYPE_CHECKING:
    from audiogen_core.composition_config_groups import (
        HarmonyTensionControlGroup,
        MelodyPhrasePlanningGroup,
        MelodyRoleDensityGroup,
        RealtimeFormGroup,
    )


@dataclass
class CompositionConfiguration(ArrangementConfiguration):
    quantization_strength: float = 0.8
    quantization_grid: int = 16
    swing_enabled: bool = False
    swing_amount: float = 0.0
    humanization_enabled: bool = False
    humanization_amount: float = 0.02
    # Higher = more motif reuse across phrases (hook-forward).
    # Default is slightly lower so continuous playback doesn't "stuck hook" per emotion.
    motif_use_chance: float = 0.90
    motif_variation_increment: float = 0.15
    motif_max_variation: float = 0.8
    use_voice_leading: bool = True
    blend_enabled: bool = True
    blend_min: float = 0.3
    blend_max: float = 0.7
    default_tempo: float = 70.0
    bass_patterns: List[List[float]] = field(default_factory=lambda: [[0.0, 2.0], [0.0, 1.0, 2.0, 3.0]])
    chord_patterns: List[List[float]] = field(
        default_factory=lambda: [[0.0], [0.0, 2.0], [0.0, 1.0, 2.0, 3.0], [0.0, 1.5, 3.0]]
    )
    use_extensions: bool = True
    extension_prob: float = 0.3
    use_modal_interchange: bool = True
    interchange_prob: float = 0.2
    use_secondary_dominants: bool = True
    secondary_dominant_prob: float = 0.15
    embellishment_prob: float = 0.2
    # Lower = more literal restatements (strong hooks, less wandering).
    # Default is higher so phrases self-variation emerges even within one emotion.
    motif_variation_prob: float = 0.12
    pop_ext_force_hook_restatement: bool = True
    hook_restatement_enabled: bool = True
    enforce_melody_climax: bool = False
    # Lock section-level arp style per emotion (mode/register/feel), tuned from gold standards.
    arp_style_table_enabled: bool = True
    # Much looser default so the arp doesn't get stuck in one repetitive bed per emotion.
    arp_style_table_strength: float = 0.35
    # Optional: chorus-only arp fit from external WAV references
    # (generated by tools/analyze_reference_wavs.py + tools/suggest_tuning_from_metrics.py).
    chorus_reference_arp_enabled: bool = False
    chorus_reference_arp_path: str = ".cache/tuning_suggestions.json"
    chorus_reference_arp_strength: float = 0.85
    # Chorus references were rendered as section peaks; scale target notes slightly
    # when applying to runtime so chorus stays energized without affecting verses.
    chorus_reference_arp_target_boost: float = 1.25
    # Optional: chorus-only melody fit from external WAV references.
    chorus_reference_melody_enabled: bool = False
    chorus_reference_melody_path: str = ".cache/tuning_suggestions.json"
    chorus_reference_melody_strength: float = 0.70
    # Scale reference notes-per-bar before blending into melody density.
    chorus_reference_melody_target_boost: float = 1.10
    # Keep chord register stable across sections by anchoring a running "chord lane".
    chord_register_anchor_enabled: bool = True
    # Lower default so progressions + voicings can drift and feel less copy/paste.
    chord_register_anchor_strength: float = 0.60
    chord_register_anchor_chorus_lift: int = 2

    # ------------------------------------------------------------------
    # Register lanes (DAW-like “range targets” per part)
    # These are *targets* used by the section planner to keep parts in a
    # consistent, produced register (reduces octave “teleports”).
    # ------------------------------------------------------------------
    melody_lane_center_midi: int = 72
    melody_lane_half_width: int = 10
    chords_lane_offset_from_melody: int = 12
    chords_lane_half_width: int = 10
    arp_lane_offset_from_melody: int = 0
    arp_lane_half_width: int = 9

    # Tension trajectory (per-bar 0..1-ish) used to co-drive multiple layers.
    tension_trajectory_enabled: bool = True
    tension_trajectory_strength: float = 0.85

    # Timeline target shaping (section planner)
    timeline_tension_spike_center: float = 0.68
    timeline_tension_spike_width: float = 0.28
    timeline_tension_spike_power: float = 1.45

    # Instrument-aware velocity curves (post-pass on events).
    velocity_curves_enabled: bool = True
    velocity_curves_strength: float = 0.2
    # Add small per-note velocity jitter to polyphonic chord hits (MIDI velocity units).
    # Set to 0 to disable. Typical realistic range: 3–8.
    chord_note_velocity_jitter: int = 5
    # Small per-note velocity jitter for monophonic parts (MIDI velocity units).
    # Set to 0 to disable. Keep small to avoid perceived dynamics shifts.
    melody_velocity_jitter: int = 5
    arp_velocity_jitter: int = 5
    bass_density: float = 2.0
    bass_style: str = "simple"
    global_scale_intervals: Optional[List[int]] = None
    # ------------------------------------------------------------------
    # Key lock (preset-facing): force all emotions into a shared key center
    # ------------------------------------------------------------------
    key_lock_enabled: bool = False
    # Fixed tonic centers (MIDI note numbers) used when key lock is enabled.
    key_lock_major_root_midi: int = 60  # C4
    key_lock_minor_root_midi: int = 57  # A3
    # Scale interval sets (relative to root) used when key lock is enabled.
    key_lock_major_scale_intervals: List[int] = field(default_factory=lambda: [0, 2, 4, 5, 7, 9, 11])
    key_lock_minor_scale_intervals: List[int] = field(default_factory=lambda: [0, 2, 3, 5, 7, 8, 10])
    # ------------------------------------------------------------------
    # Per-song key variation: transpose each generated song to a fresh tonic
    # so successive generations of the same emotion aren't always in C.
    # Applied ONLY when key_lock is off (key_lock takes precedence). The whole
    # song derives from one root, so this is a coherent transposition (melody,
    # harmony and bass all move together). Offsets are semitones from the base
    # root (60); the pool is kept within a comfortable octave to preserve the
    # emotion's register and stay in sample range.
    # ------------------------------------------------------------------
    key_variation_enabled: bool = True
    key_variation_root_offsets: List[int] = field(default_factory=lambda: [-5, -3, -2, 0, 2, 4, 5, 7])
    # Avoid immediately repeating the previous song's key (more perceived variety).
    key_variation_avoid_immediate_repeat: bool = True
    # ------------------------------------------------------------------
    # Per-song tempo jitter: small +/- variation around the emotion's base tempo
    # so successive generations of the same emotion don't always land at the
    # exact same bpm. Applied as a multiplier on base_tempo_bpm, so it composes
    # cleanly with the existing emotion tempo_multiplier.
    # ------------------------------------------------------------------
    tempo_variation_enabled: bool = True
    tempo_variation_max_pct: float = 0.06  # +/- 6%
    # If true, quantize generated chord tones to the emotion scale (unless a global_scale is explicitly set).
    force_emotion_scale_quantization: bool = True
    # Derive a compatible scale from the emotion's chord pools (union of chord tone pitch classes),
    # so strict quantization doesn't neutralize intended harmony.
    derive_emotion_scale_from_chords: bool = True
    use_policy_phrase_contour_override: bool = True
    humanization_probability: float = 0.3
    # Stronger anti-repeat pressure so progressions evolve more.
    chord_repeat_penalty: float = 0.85
    max_chord_repeats: int = 1
    force_change_prob: float = 0.30
    drone_always_on: bool = False
    drone_fixed_midi: Optional[int] = None
    # Live playback: keep the drone continuous across emotion/root switches (no restart, no retune).
    # This does NOT force the drone to be enabled; it only prevents resetting its locked pitch/state.
    drone_keep_playing_on_switch: bool = True
    stable_emotion_dynamics: bool = True
    global_tempo_scale: float = 1.0
    # Global lead density scaler (lower = fewer melody notes overall).
    melody_amount_scale: float = 0.82
    neural_phrase_generator_enabled: bool = False
    # How strongly to enforce per-emotion melody behaviour profiles (0..1).
    # Higher values push density/register/rhythm closer to emotion-specific targets.
    emotion_melody_strictness: float = 0.7
    # Global multiplier on top of emotion-driven density (1.0 = neutral).
    emotion_melody_density_bias: float = 1.0
    # Global transpose offset applied to emotion-driven melody registers (in semitones).
    emotion_melody_register_bias_semitones: int = 0
    # Global multiplier on Markov rest probability (higher = more gaps).
    # Lower = fewer gaps in the lead so motifs read clearly.
    melody_rest_prob_mult: float = 0.88
    # Rest-insertion guardrail: keep at least this fraction of planned melody
    # notes per bar voiced, bounded by floor/ceiling below.
    melody_rest_min_voiced_bar_enabled: bool = True
    melody_rest_min_voiced_bar_ratio: float = 0.58
    melody_rest_min_voiced_bar_floor: int = 2
    melody_rest_min_voiced_bar_ceiling: int = 6
    # Repetition breaker threshold (higher = fewer replaced notes).
    melody_break_repeat_max: int = 6
    # Section-role melody density multipliers (Markov lead).
    # These are applied on top of emotion/profile/timeline shaping so section
    # roles read more distinctly (e.g. intro/outro sparser, chorus fuller).
    # Grouped read access: `melody_role_density` -> `core.composition_config_groups.MelodyRoleDensityGroup`.
    melody_role_density_intro_mult: float = 0.90
    melody_role_density_verse_mult: float = 0.98
    melody_role_density_prechorus_mult: float = 1.04
    melody_role_density_chorus_mult: float = 1.10
    melody_role_density_tag_mult: float = 1.06
    melody_role_density_aprime_mult: float = 1.02
    melody_role_density_outro_mult: float = 0.68
    # Soft role caps/floors for target notes-per-bar after role multiplier.
    # Keep intros/outros from over-singing; keep choruses from collapsing.
    melody_role_intro_target_npb_max: float = 4.2
    melody_role_intro_target_npb_min: float = 2.9
    melody_role_verse_target_npb_min: float = 3.8
    melody_role_prechorus_target_npb_min: float = 4.8
    melody_role_outro_target_npb_max: float = 3.8
    melody_role_chorus_target_npb_min: float = 5.6
    # If arp is active in chorus-like roles, scale melody total-note budget by this
    # to create a clearer "arp bed + slower lead answer" relationship.
    # Default near 1.0 so the lead can stay present alongside a busy arp; lower values
    # thin the melody when you want stronger call/response.
    chorus_melody_duck_with_arp: float = 1.0
    # When True, keep the legacy "answer after the arp bed" entrance delays (up to ~1 bar).
    # Default False: melody can enter with the arp instead of waiting for space.
    melody_arp_call_response_delay_enabled: bool = False
    # When True, pass arp-derived occupied intervals into melody Markov as soft "anti-collision"
    # weights (call/response). When False, melody + arp are allowed to freely overlap.
    melody_arp_occupied_masking_enabled: bool = False
    # Coexistence tuning: arp occupancy is passed into Markov as soft masking weights.
    # Scale <1.0 makes the lead less likely to duck/rhythm-shift away from the arp grid.
    melody_arp_occupied_weight_global_scale: float = 0.62
    # Extra attenuation applied only when arp-derived occupied masking is active.
    melody_arp_mask_strength_scale_when_arp_masking: float = 0.55
    # If the realized lead median sits at/below the arp median (same register), lift
    # the whole lead by one octave when there is headroom under the melody ceiling.
    melody_octave_lift_vs_arp_when_median_at_or_below_arp: bool = True
    melody_octave_lift_vs_arp_max_median_gap_semitones: int = 2
    melody_octave_lift_vs_arp_min_headroom_semitones: int = 2
    # After arp is finalized: nudge individual lead notes by ±12 when they overlap the arp
    # in time and are within `melody_arp_clash_max_semitones` (0 = unison only).
    melody_octave_resolve_arp_clash_enabled: bool = True
    melody_arp_clash_max_semitones: int = 0
    melody_arp_clash_octave_resolve_prefer_up: bool = True
    # Late planner/finalize nudges that pushed chorus leads off integer beats vs dense arps.
    melody_chorus_strong_beat_shift_vs_arp_enabled: bool = False
    melody_dense_arp_downbeat_nudge_enabled: bool = False

    # ------------------------------------------------------------------
    # Arpeggiator octave behavior (Ableton-like occasional +12 reach)
    # ------------------------------------------------------------------
    # If True, allow the arp bed to occasionally jump an octave up on weak steps.
    arp_octave_reach_enabled: bool = True
    # Global multiplier on the engine's computed octave reach probability.
    # (0 disables; 1 keeps emotion-derived defaults; >1 makes more octave jumps.)
    arp_octave_reach_strength: float = 1.0
    # On the last arp grid step of a bar, with this probability, nudge the pitch toward
    # the *next* bar's chord (anticipation color). Default 0 keeps arp notes within the
    # chord pool for the active harmonic-rhythm step (same-time with the progression).
    arp_next_bar_last_step_hint_prob: float = 0.0
    # Occasionally replace an arp step with a sustained tonic/fifth note (+octave),
    # lasting the full chord (bar) duration.
    arp_tonic_fifth_drone_note_enabled: bool = False
    arp_tonic_fifth_drone_note_prob: float = 0.0
    arp_tonic_fifth_drone_note_octave_semitones: int = 12
    # Pre-compute harmonic-rhythm Markov actions once per section (deterministic side-RNG) and
    # reuse them in both the arpeggiator and chord comping so arp chord-index steps match pads.
    arp_chord_harmonic_rhythm_shared_enabled: bool = True
    cadence_strength: float = 1.30
    melody_cadence_strength: float = 1.25
    # Harmony-function contracts: strengthen T/PD/D targets near phrase boundaries.
    harmony_function_contracts_enabled: bool = True
    harmony_function_contract_strength: float = 0.72  # 0..1
    use_rhythmic_chord_layers: bool = True
    chord_hits_decouple_from_changes: bool = True
    # Allow intra-bar harmonic changes (2 or 3 chord targets within a bar) when harmonic rhythm is high.
    chord_intra_bar_change_enabled: bool = True
    chord_intra_bar_change_strength: float = 0.25  # 0..1
    chord_intra_bar_change_max_splits: int = 3      # 1=off, 2=two-per-bar, 3=three-per-bar

    # ------------------------------------------------------------------
    # Realtime harmony tension control
    # ------------------------------------------------------------------
    # Grouped read access: `harmony_tension` -> `HarmonyTensionControlGroup` in
    # `core.composition_config_groups`.
    # Ties augmentation frequency (secondary dominants / modal interchange / chord
    # extensions — see chord_utils.py) to each section's tension level, which is
    # itself derived from the emotion's own tension-arc template
    # (data/tension_arc_dynamics.py). Was a documented but disabled (0.0) no-op;
    # enabled 2026-07-02 as part of tightening emotion accuracy in the harmony
    # augmentation layer — see docs/AUDIOGEN_COMPOSITION_PLAN.md item 9. Calm
    # moments get restrained harmonic color (low cap), tense moments keep full
    # baseline color (high cap stays at the historical no-op value of 1.0) —
    # this only ever *reduces* color relative to before, never adds beyond it,
    # so it's a safe first step to validate by ear before going further.
    # 0..1: master strength for tension-shaped harmony motion (color caps + HR bias).
    harmony_tension_control_strength: float = 0.7
    # 0..1: multiplicative cap applied to chord color probabilities at low tension.
    harmony_color_cap_low_tension: float = 0.5
    # 0..1: multiplicative cap applied to chord color probabilities at high tension.
    harmony_color_cap_high_tension: float = 1.0
    # 0..1: sensitivity of harmonic rhythm choices to per-bar tension.
    harmonic_rhythm_tension_sensitivity: float = 0.4
    # Section-role harmony pacing: verse/intro/outro hold more, pre-chorus moves
    # more, chorus stabilizes for hooks, bridge/a_prime can carry a surprise chord.
    harmony_pacing_policy_enabled: bool = True
    harmony_pacing_policy_strength: float = 1.0

    # ------------------------------------------------------------------
    # Markov style consistency (defaults are no-op)
    # ------------------------------------------------------------------
    # 0..1: master strength for style-profile reweighting across Markov layers.
    markov_style_strength: float = 0.45

    # Longform contrast scheduling (helps continuous playback avoid "samey" sections)
    contrast_every_n_sections: int = 2
    contrast_strength: float = 0.42  # 0..1

    # ------------------------------------------------------------------
    # Realtime form scheduling (non-arranged continuous playback)
    # ------------------------------------------------------------------
    # Grouped read access: `realtime_form` -> `RealtimeFormGroup` in `core.composition_config_groups`.
    # If enabled, the realtime player loops the form body (e.g. A→pre→B→A→B…)
    # instead of getting stuck in the terminal role of the form sequence.
    realtime_form_loop_enabled: bool = True
    # Optional: override which form sequence to loop (uses `ArrangementPolicy.form_mode` when empty).
    # Examples: "default", "pop", "pop_ext", "rondo", "ballad", "wave"
    realtime_form_mode_override: str = ""
    # If True, omit any terminal "outro" role from the loop body.
    realtime_form_loop_drop_outro: bool = True
    # When ``CompositionGenerator.runtime_generation_mode`` is not ``normal`` (live player ladder),
    # optionally cap expensive planning passes. ``full`` preserves legacy behavior.
    # ``light`` reduces best-of-K section picks and joint-generation iterations.
    # ``minimal`` forces the fastest section path and skips global voice-leading optimisation.
    realtime_planner_effort: str = "full"

    # ------------------------------------------------------------------
    # Realtime texture + form gestures
    # ------------------------------------------------------------------
    # 0..1: drop/thinning strength around breath/cadence/build moments.
    texture_drop_strength: float = 0.45
    # 0..1: amount of chorus/tag register lift applied in finalize shaping.
    texture_register_lift_strength: float = 0.55
    # 0..1: enable per-bar FX gestures (space/width/grit) driven by bar trace.
    texture_fx_gesture_strength: float = 0.32
    # Section-level energy arc length for realtime looping (used to compute rt_energy).
    realtime_energy_arc_length: int = 8

    # Arrangement energy matrix:
    # role-aware per-lane/per-target scaling (melody/chord/motif/tension + layer presence)
    # applied on top of timeline targets to make form contrast audibly stronger.
    arrangement_energy_matrix_enabled: bool = True
    arrangement_energy_matrix_strength: float = 0.72  # 0..1
    # Whole-song director:
    # applies a global intro->verse->pre->chorus->return->payoff energy arc on top
    # of local role curves so arranged renders read as full songs, not adjacent loops.
    whole_song_director_enabled: bool = True
    whole_song_director_strength: float = 0.68
    whole_song_final_chorus_lift: float = 0.14
    whole_song_chorus_hook_memory_enabled: bool = True
    whole_song_chorus_hook_memory_strength: float = 0.78

    # 16-bar A/B development intent: how much the second half should evolve
    # (more motion/motif, slightly higher density). Used by SectionPlanner timeline targets.
    ab_development_strength: float = 0.15  # 0..0.5

    # Cinematic chord comping patterns (deterministic vocabulary, not pure randomness).
    chord_comping_enabled: bool = True
    chord_comping_strength: float = 0.8  # 0..1 (how often to use vocab vs fallback heuristics)
    chord_comping_anticipation_prob: float = 0.06  # cinematic: rare

    # Phrase defaults (bars). Used across harmony/microtiming/voicing to keep
    # section structure coherent and configurable.
    phrase_length_bars: int = 4
    # Larger structural boundary (e.g. A/B split in 16-bar sections).
    superphrase_length_bars: int = 8

    # Live transition (emotion switch) shaping
    transition_enabled: bool = True
    # Minimum shared pitch classes for bar-0 chord pivot selection.
    transition_common_tone_min: int = 1
    # If True, avoid motif-first openings on the first phrase after a handoff.
    transition_disable_motif_first: bool = True
    # After a manual emotion switch, blend the first N bars of per-bar generation targets
    # (melody density / chord rhythm / tension / motif strength) from the previous emotion
    # into the new emotion to avoid an abrupt musical jump. 0 disables blending.
    transition_blend_bars: int = 4
    # Optional “bridge” window right after a manual emotion switch.
    # - transition_bridge_bars: conceptual bridge length (used by planners as a cap / tuning hint).
    # - transition_bridge_hold_bars: number of initial bars that should hold strong continuity
    #   anchors from the outgoing section (previous bass note, high common-tone chord pivot).
    transition_bridge_bars: int = 4
    transition_bridge_hold_bars: int = 2
    # Stronger phrase-aware handoff shaping near section endings.
    transition_composer_phrase_handoff_enabled: bool = True
    transition_composer_phrase_handoff_strength: float = 0.82
    # Slow harmonic center drift across sections (keeps long playback evolving
    # while still returning toward tonal home near the form end).
    tonal_center_drift_enabled: bool = True
    tonal_center_drift_strength: float = 0.55
    tonal_center_drift_max_semitones: int = 3
    tonal_center_drift_cycle_sections: int = 8
    melody_target_notes_per_bar: float = 6.0
    melody_register_arc_enabled: bool = True
    seed: Optional[int] = None
    # True when the user explicitly passes `--seed` (repeatable runs). Used to decide
    # whether realtime-only previews may inject extra randomness beyond the base seed.
    user_pinned_seed: bool = False
    deterministic_seeded_offline_renders: bool = True
    # If True, clicking/selecting an emotion in generative mode reseeds + resets song memory
    # so you get a fresh variation instead of replaying the same deterministic generation.
    reseed_on_emotion_change_enabled: bool = True
    chord_k_samples: int = 3
    chord_rerank_change_bonus: float = 0.10
    chord_rerank_cadence_bonus: float = 0.14
    # Slightly hotter chord sampling = more different progressions per run.
    chord_temp_opening_mult: float = 1.10
    chord_temp_continuation_mult: float = 1.12
    chord_temp_answer_mult: float = 1.06
    chord_temp_cadence_mult: float = 0.98
    # Grouped read access (phrase beam / rerank / scorers): `melody_phrase_planning`.
    melody_k_samples: int = 4
    # Phrase-level best-of-K (select the most "composed" phrase among K samples).
    # Phrase-level best-of-K: higher yields more "composed" motifs at some CPU cost.
    melody_phrase_k_samples: int = 3
    # Phrase beam rerank: wider candidate frontier + shortlist rerank.
    melody_phrase_beam_enabled: bool = True
    melody_phrase_beam_width: int = 7
    melody_phrase_beam_keep: int = 3
    melody_phrase_beam_diversity_weight: float = 0.12
    melody_phrase_beam_lookahead_weight: float = 0.18
    # Phrase rerank memory model: balance immediate novelty with structural recall.
    melody_listener_memory_scorer_enabled: bool = True
    melody_listener_memory_scorer_strength: float = 0.68
    # Lyrical-minimalist beauty scorer: rewards stepwise motion, recoveries after
    # leaps, small recurring motifs, breath, stable cadences, and focused range.
    lyrical_melody_scorer_enabled: bool = True
    lyrical_melody_scorer_strength: float = 0.48
    melody_phrase_rerank_entry_leap_penalty: float = 0.26
    melody_phrase_rerank_large_leap_penalty: float = 0.06
    melody_phrase_rerank_large_leap_threshold: int = 4
    melody_phrase_rerank_cadence_land_bonus: float = 0.55
    melody_phrase_rerank_cadence_approach_bonus: float = 0.24
    melody_phrase_rerank_cadence_miss_penalty: float = 0.22
    melody_rerank_opening_stepwise_bonus: float = 0.08
    melody_rerank_opening_chord_tone_bonus: float = 0.07
    melody_rerank_cadence_target_bonus: float = 0.18
    melody_rerank_cadence_approach_bonus: float = 0.05
    melody_rerank_mid_contour_bonus: float = 0.04
    melody_rerank_motif_continue_bonus: float = 0.05
    # Short-horizon lookahead for rerank (phrase openings/cadences).
    melody_rerank_lookahead_weight: float = 0.22
    melody_rerank_lookahead_top_m: int = 7
    # 0..1: promotes ai/markov/melody/beauty.py's "leap recovery" scoring signal (does a
    # leap get followed by a step back — the classic melody-writing rule) from a post-hoc
    # rerank-only nudge into an active generation-time bias. Added 2026-07-02, see
    # docs/AUDIOGEN_COMPOSITION_PLAN.md item 14. 0 = no bias (old behavior, rely on rerank
    # alone); higher values more strongly favor a stepwise interval immediately after a
    # wrapped-distance-3+ leap.
    melody_leap_recovery_bias_strength: float = 0.35
    # <1.0 in chorus(-like) roles: slightly more leaps / color vs chord-on-every-beat blandness.
    melody_role_chorus_stepwise_mult: float = 0.90
    melody_role_chorus_chord_tone_mult: float = 0.94
    melody_role_verse_leap_mult: float = 1.0
    melody_role_outro_stepwise_mult: float = 1.0
    # Joint fit: on strong beats, bias interval selection toward chord tones (degree-space).
    # 1.0 = neutral; >1.0 improves chord-tone fit (can reduce melodic "spice" if too high).
    melody_strongbeat_chord_tone_mult: float = 3.25
    # Strong-beat chord-tone contract:
    # when enabled, notes that start on strong beats and are "long enough" are
    # heavily discouraged from landing on non-chord tones (phrase-level logic also helps,
    # but this is a per-note guardrail).
    melody_strongbeat_chordtone_contract_enabled: bool = True
    # Duration (in beats) above which the chord-tone contract is enforced more strongly.
    melody_strongbeat_chordtone_contract_min_duration_beats: float = 0.25
    # Multiplicative penalty applied to non-chord landings under the contract (0..1).
    melody_strongbeat_chordtone_contract_nonchord_mult: float = 0.035

    # Soft register preference for melody interval sampling:
    # penalize choosing next notes outside the channel's preferred range (clamping is a last resort).
    melody_register_preference_enabled: bool = True
    melody_register_preference_strength: float = 0.35  # 0..1

    # Joint duration×interval rerank (rhythm-first path):
    # sample top-K durations and top-M intervals, score pairs, softmax-pick one.
    melody_joint_duration_interval_rerank_enabled: bool = True
    melody_joint_duration_interval_rerank_strength: float = 0.85  # 0..1
    melody_joint_duration_interval_top_k_durations: int = 6
    melody_joint_duration_interval_top_m_intervals: int = 10
    # Temperature applied to the softmax over candidate pair scores (lower = more deterministic).
    melody_joint_duration_interval_softmax_temp: float = 0.65

    # Harmony anti-stuck: discourage repeating the last chord token.
    harmony_antistuck_enabled: bool = True
    harmony_repeat_penalty_mult: float = 0.55
    melody_avoid_recent_openings: bool = True
    melody_opening_max_attempts: int = 2
    melody_opening_temp_bump: float = 0.08
    melody_register_filter_enabled: bool = True
    melody_bass_contrary_bonus_mult: float = 1.0
    melody_bass_parallel_penalty_mult: float = 1.0
    # Learn + use phrase-role conditioned interval models (opening/answer/cadence).
    melody_train_phrase_role_models: bool = True
    # Blend factor for phrase-role interval probs into the base interval probs.
    melody_phrase_role_model_blend: float = 0.50
    # Blend factor for phrase-role rhythm probs into the base rhythm probs.
    melody_phrase_role_rhythm_model_blend: float = 0.25
    # Runtime enable/disable for role-conditioned models (interval + rhythm).
    melody_role_conditioning_enabled: bool = True

    # ------------------------------------------------------------------
    # Live emotion switching latency control (realtime player)
    # ------------------------------------------------------------------
    # If enabled, when the user queues an emotion change (e.g. via `n`), the pre-generation
    # thread will first generate a short "handoff chunk" (a few bars) so the audible switch
    # can happen quickly. The normal pipeline will then build the full next section in the
    # background. This reduces perceived latency without requiring risky buffer trimming.
    emotion_switch_fast_chunk_enabled: bool = True
    emotion_switch_fast_chunk_bars: int = 4

    # ------------------------------------------------------------------
    # Timing: hard grid quantization (DAW-like)
    # ------------------------------------------------------------------
    # If enabled, all event onsets will be snapped to a 16th-note grid (1/16).
    # When enabled, microtiming/swing layers should be disabled to avoid fighting the grid.
    quantize_16th_enabled: bool = True
    # Quantize policy: start-only preserves musical note lengths while aligning timing.
    quantize_16th_mode: str = "start_only"  # "start_only" | "start_and_end"

    # Phrase intent biasing (register + hook anchor).
    melody_intent_enabled: bool = True
    melody_intent_register_strength: float = 0.35   # 0..1
    melody_hook_anchor_strength: float = 0.25       # 0..1

    # ------------------------------------------------------------------
    # Composition↔Markov synergy controls (intent + temperature + voicing glue)
    # ------------------------------------------------------------------
    # 0..1: how strongly per-bar harmony intent (T/PD/D + cadence strength) nudges rhythm sampling.
    melody_intent_rhythm_strength: float = 0.18
    # 0..1: how strongly per-bar harmony intent nudges interval sampling (goal-directed motion).
    melody_intent_interval_strength: float = 0.22

    # Per-bar temperature shaping from timeline intent (tension + melody activity).
    melody_bar_temperature_scaling_enabled: bool = True
    melody_bar_temperature_scaling_strength: float = 0.22  # 0..1
    melody_bar_temperature_tension_ref: float = 0.85
    melody_bar_temperature_activity_ref: float = 1.0
    melody_bar_temperature_activity_weight: float = 0.12   # 0..0.5
    melody_bar_temperature_mult_min: float = 0.80
    melody_bar_temperature_mult_max: float = 1.35

    # Voiced-chord pitch-class affinity (soft glue between harmony voicings and melody).
    melody_voiced_chord_pc_affinity_enabled: bool = True
    melody_voiced_chord_pc_affinity_strength: float = 0.18  # 0..1

    # Chords↔melody onset dialogue: avoid masking the lead on its planned onsets.
    chords_avoid_melody_onsets_enabled: bool = True
    chords_avoid_melody_onsets_strength: float = 1.0  # 0..1
    chords_avoid_melody_onsets_grid_beats: float = 0.25

    # Debug: record per-bar intent + temperature used by Markov melody generation.
    debug_melody_intent_trace_enabled: bool = False
    # Blend global Markov statistics into per-emotion melody Markov.
    # 0.0 = only emotion-trained Markov; 1.0 = only global Markov.
    melody_global_markov_blend: float = 0.24
    # Condition melody intervals on (chord function × phrase role × bar-in-phrase).
    melody_function_condition_blend: float = 0.50
    # Condition melody rhythms on (chord function × phrase role × bar-in-phrase).
    melody_function_rhythm_condition_blend: float = 0.35
    # Optional hierarchical context tags for function-conditioned Markov features.
    # Adds song-level hints (section role + tension/cadence bands) to function keys,
    # with runtime backoff to the existing feature key when sparse.
    melody_function_context_hierarchy_enabled: bool = True
    melody_function_context_hierarchy_strength: float = 0.45

    # Beat-strength conditioning: separate Markov statistics on downbeat vs offbeat.
    melody_beat_strength_conditioning_enabled: bool = True
    melody_beat_strength_condition_blend: float = 0.22

    # Register-band conditioning: learn different interval/rhythm tendencies in low/mid/high ranges.
    melody_register_band_conditioning_enabled: bool = True
    melody_register_band_condition_blend: float = 0.22
    melody_register_band_low_max_midi: int = 59
    melody_register_band_high_min_midi: int = 73

    # Variable-order Markov: require a minimum empirical total for a context length
    # before using it (otherwise back off automatically).
    markov_variable_order_min_total: int = 8
    melody_antistuck_enabled: bool = True
    melody_loop_penalty_mult: float = 0.5
    melody_rhythm_repeat_penalty_mult: float = 0.85

    # Phrase-state conditioning:
    # applies a lightweight opening/continuation/answer/cadence plan to phrase
    # contours + note-budget allocation before Markov decoding.
    phrase_state_conditioning_enabled: bool = True
    phrase_state_conditioning_strength: float = 0.72  # 0..1

    # Cadence contracts:
    # post-pass that hardens phrase-end landings (target + approach + hold length).
    cadence_contracts_enabled: bool = True
    cadence_contracts_strength: float = 0.76  # 0..1

    # Cross-lane motif bus:
    # share lightweight motif cells between lead/arp/counter layers.
    cross_lane_motif_bus_enabled: bool = True
    cross_lane_motif_bus_strength: float = 0.82  # 0..1

    # Offline quality render mode:
    # boost sampling/rerank depth for non-realtime renders.
    offline_quality_render_enabled: bool = False
    offline_quality_k_scale: float = 1.6
    offline_quality_beam_width: int = 10

    # Dynamic anti-repetition (n-gram penalty) for lead melody.
    melody_ngram_penalty_enabled: bool = True
    melody_ngram_window_tokens: int = 36
    melody_ngram_decay: float = 0.90
    melody_ngram_penalty_strength: float = 0.45

    # Harmony development scheduling (16-bar arc).
    harmony_development_enabled: bool = True
    harmony_development_strength: float = 0.25  # 0..1
    harmony_cadence_tighten_strength: float = 0.35  # 0..1
    harmony_function_diversity_guardrail_enabled: bool = True
    harmony_function_diversity_window: int = 4
    harmony_function_diversity_strength: float = 0.35  # 0..1
    harmony_markov_use_degree_tokens: bool = True
    harmony_markov_degree_backoff_blend: float = 0.35
    harmony_markov_debug_trace_enabled: bool = False

    # Markov smoothing/backoff tuning
    # Higher backoff_decay => trust higher-order contexts more (slower backoff).
    # Lower => blend more aggressively toward lower-order/global distribution.
    markov_backoff_decay: float = 0.84

    # Conditioned Markov guardrails: prevent sparse conditioned models from destabilizing output.
    markov_condition_min_contexts: int = 24
    markov_condition_min_vocab: int = 6

    # Live dataset logging (optional): write generated melodies to JSONL so you can train
    # Markov models on your own outputs + planner roles/contours.
    export_live_melody_training_enabled: bool = False
    export_live_melody_training_path: str = ".cache/live_melody_training.jsonl"
    # Full joint dataset logging (optional): write multi-part rows (bass + chords + lead + arp + counter)
    # aligned to the section's harmonic plan so you can train per-part Markovs from a shared corpus.
    export_live_joint_training_enabled: bool = False
    export_live_joint_training_path: str = ".cache/live_joint_training.jsonl"
    # Runtime load of a retrained melody MarkovModelSet pickle generated by
    # scripts/melody_jsonl_retrain.py (keeps the system self-generative while adapting
    # to your own generated corpus over time).
    # 2026-07-04: default-ON. The trained model at the path below wakes up the interval
    # Markov (0% -> 99.8% real per-note probabilities; the untrained path is inert per
    # docs/AUDIOGEN_COMPOSITION_PLAN.md item 17), giving richer melodies. After the
    # bundle-cache + reload-stall fixes it is real-time-safe on every emotion (0 underruns;
    # see the "Efficiency + underrun investigation" section of the plan doc). Fallback is
    # safe: if the file below is missing, loading is skipped and the default melody path is
    # used unchanged (empirically verified -- varied melodies, no degeneration). Set to
    # False (or pass --no-melody-retrained-markov) to force the faster untrained path.
    melody_retrained_markov_enabled: bool = True
    melody_retrained_markov_path: str = "training_data/active_models/melody_markov.pkl"
    # 2026-07-04: load the ~196MB retrained bundle on a background thread instead of
    # blocking CompositionGenerator construction (~6s). The first few sections generate
    # with the default (untrained) melody path and quietly upgrade to the retrained model
    # once the load completes -- cutting realtime time-to-first-audio by ~6s. Default False
    # so offline/batch export stays deterministic (blocks until loaded, first section is
    # already retrained); the realtime player sets it True. Safe because per-section
    # hot-reload is off by default, so the construction load is the only load, and binding
    # happens on the generation thread (no cross-thread races).
    melody_retrained_markov_async_load: bool = False
    # Optional hot-reload: periodically check file mtime and reload retrained Markov
    # while playback is running (no restart needed).
    melody_retrained_markov_hot_reload_enabled: bool = False
    melody_retrained_markov_hot_reload_interval_seconds: float = 2.0

    # Optional runtime load of retrained chord Markov bundle generated by
    # scripts/chord_jsonl_retrain.py.
    chord_retrained_markov_enabled: bool = False
    chord_retrained_markov_path: str = "training_data/active_models/chord_markov.pkl"
    chord_retrained_markov_hot_reload_enabled: bool = False
    chord_retrained_markov_hot_reload_interval_seconds: float = 2.0

    # ------------------------------------------------------------------
    # Note logging (audit “log sheet”)
    # ------------------------------------------------------------------
    # If enabled, append one CSV row per generated note (post-humanization)
    # to `note_log_path`. This is intended for musical auditing (in-key checks).
    note_log_enabled: bool = True
    note_log_console_enabled: bool = False
    note_log_path: str = "logs/note_log.csv"

    # ------------------------------------------------------------------
    # Dataset-driven arrangement prior (realtime-safe)
    # ------------------------------------------------------------------
    # If enabled, arranged-song generation (live playback) will consult the exported
    # melody-training JSONL dataset to choose arrangement mode + sizing knobs, while
    # still using the existing SongGenerator forms and emotion chord sets.
    dataset_arrangement_enabled: bool = False
    # Hard cap on dataset-driven live best-of-K pick time (seconds).
    dataset_arrangement_pick_budget_s: float = 1.25
    # If enabled, append one JSONL line per arranged-song generation for debugging/A-B.
    dataset_arrangement_trace_enabled: bool = False
    dataset_arrangement_trace_path: str = ".cache/dataset_arrangement_trace.jsonl"

    # Section-level best-of-K (global scorer across parts).
    section_k_samples: int = 3
    section_pick_time_budget_s: float = 0.75
    # When True, stop best-of-K after `section_pick_time_budget_s` (live generative).
    # Set False for deterministic offline/seeded runs that need exact attempt counts.
    section_pick_use_wall_clock: bool = True
    # Musical rerank layer on top of the section scorer. This keeps the base
    # arrangement score intact, then nudges best-of-K toward lyrical toplines and
    # away from stale whole-song repetition.
    section_sampler_musical_rerank_enabled: bool = True
    section_sampler_lyrical_weight: float = 0.30
    section_sampler_lyrical_target: float = 0.58
    section_sampler_harmony_repeat_penalty: float = 0.10
    section_sampler_register_stasis_penalty: float = 0.06
    # Novelty/contrast term for best-of-K section selection:
    # encourages non-identical chord openings and gentle register drift so long-form
    # playback feels like evolving scenes (Citizen Sleeper / ambient narrative).
    section_sampler_novelty_enabled: bool = True
    # Overall weight applied to the novelty bonus (positive = prefer novelty).
    section_sampler_novelty_weight: float = 0.28
    # Reward chord-opening novelty vs recent chord signatures (0..1-ish).
    section_sampler_chord_novelty_weight: float = 0.24
    # Reward register drift toward a target distance (in MIDI semitones).
    section_sampler_register_novelty_weight: float = 0.14
    section_sampler_register_drift_target_semitones: float = 4.0
    section_sampler_register_drift_sigma_semitones: float = 3.0
    section_sampler_debug_report_enabled: bool = True

    # Offline (quality-first) best-of-K section selection (used by offline renders).
    bestofk_enabled: bool = True
    bestofk_k: int = 4
    bestofk_temperature_jitter: float = 0.08
    # Whole-song best-of-K narrative rerank (SongGenerator.generate_song_best_of_k).
    whole_song_rerank_enabled: bool = True
    whole_song_rerank_blueprint_weight: float = 0.55
    # Phase A upgrade: blend whole-song rerank with batch-audit composite score.
    song_upgrade_phase_c_enabled: bool = False
    song_upgrade_phase_a_enabled: bool = False
    audit_aligned_rerank_enabled: bool = False
    audit_aligned_rerank_weight: float = 0.55
    # Phase B: ridge reranker trained from audit ``run_summary.csv`` (JSON weights file).
    song_upgrade_phase_b_enabled: bool = False
    song_rerank_model_path: str = ""
    song_rerank_log_enabled: bool = False
    song_rerank_log_path: str = "artifacts/datasets/song_rerank/candidates.jsonl"

    # Phase 11: closed-loop adapter settings
    bass_velocity_multiplier: float = 1.0
    counter_melody_octave_offset: int = 0

    # Song-level blueprint planner (global narrative targets consumed by section generation).
    song_blueprint_enabled: bool = True
    song_blueprint_apply_targets_enabled: bool = True
    song_blueprint_target_strength: float = 0.72

    # Cadence-first harmony steering from song blueprint (open vs closed vs deceptive arrivals).
    cadence_first_harmony_enabled: bool = True
    cadence_first_harmony_strength: float = 0.78

    # Motif lifecycle orchestration (introduce/develop/restate/payoff/fragment).
    motif_lifecycle_enabled: bool = True
    motif_lifecycle_strength: float = 0.86

    # Arrangement contracts: role-aware lane occupancy envelopes.
    arrangement_contracts_enabled: bool = True
    arrangement_contracts_strength: float = 0.72

    # Chord Markov phrase-role conditioning (opening/answer/cadence).
    chord_phrase_role_markov_blend: float = 0.28

    # Bias template selection toward extension-rich progressions (those that already contain
    # explicit 7/9/11/13/add9/6/9 symbols). This only affects the *template pick* in
    # `ChordPlanner.generate_chord_progression` (best-of-K sampling), not the Markov walk itself.
    # 0.0 disables the bias, 1.0 always prefers extension-rich templates when available.
    prefer_extension_rich_progressions_prob: float = 0.0

    # ------------------------------------------------------------------
    # Chord progression data source
    # ------------------------------------------------------------------
    # If True, chord progressions are selected from the emotion pool and replayed
    # (tiled to section length) instead of being sampled by the chord Markov process.
    # This makes chord progressions the fixed “backbone” that bass/melody/arp follow.
    chord_progression_replay_enabled: bool = False

    # If True, build/train the chord Markov models from the in-repo emotion chord pools
    # at runtime initialization. This is lightweight and makes Markov probabilities
    # reflect the curated progression dataset in `data/music_data.py`.
    chord_markov_train_from_pools: bool = True

    # Harmonic rhythm chooser (hold/half/anticipate/sus) conditioned by phrase role.
    harmonic_rhythm_markov_enabled: bool = True
    harmonic_rhythm_markov_strength: float = 0.7

    # Voice-leading "predictability": also bias choices to keep close to the *next* chord.
    # 0.0 disables lookahead, 1.0 is strong lookahead. Keep modest to avoid freezing inversions.
    chord_voicing_lookahead_strength: float = 0.35
    # Extra penalties to keep chord voicing motion piano-like (avoid dramatic register jumps).
    # These apply inside the global voice-leading beam search.
    chord_voice_max_leap_semitones: int = 7
    chord_voice_leap_penalty: float = 3.0
    chord_center_jump_penalty: float = 2.0
    # Strong guide-tone continuity: keep 3rd/7th stable across bar boundaries.
    chord_guide_tone_anchor_enabled: bool = True
    chord_guide_tone_anchor_weight: float = 1.25
    chord_guide_tone_max_motion_semitones: int = 3
    # Keep comping voicings lean (more piano-like). 4–5 is typical for “produced” pads.
    max_chord_tones_in_voicing: int = 8
    # Allow richer chord colors in voicings (9/11/13) and 10ths (3rd up an octave).
    chord_voicing_allow_extensions: bool = True
    chord_voicing_allow_tenths: bool = True

    # Chord voicing quality terms (used in global voice-leading optimiser).
    chord_voicing_mud_threshold_midi: int = 40  # ~E2
    chord_voicing_mud_penalty: float = 0.55
    chord_voicing_low_spacing_threshold_midi: int = 52  # ~E3
    chord_voicing_low_spacing_min_semitones: int = 4
    chord_voicing_spacing_penalty: float = 0.35
    chord_voicing_top_continuity_bonus: float = 0.40
    chord_voicing_top_continuity_max_semitones: int = 7

    # Hard anti-cluster guardrails (applied when enumerating voicing candidates).
    # If enabled, candidates that violate spacing/span thresholds are removed from the search pool.
    chord_voicing_hard_cluster_reject: bool = True
    # Minimum overall chord span (top - bottom) required for 3- and 4-tone comping voicings.
    chord_voicing_min_span_3_tones_semitones: int = 10
    chord_voicing_min_span_4_tones_semitones: int = 14

    # ------------------------------------------------------------------
    # Hook-safe composition mode (high-level preset)
    # ------------------------------------------------------------------
    # When true, higher-level helpers (e.g. ConfigurationManager) may choose to
    # apply a more conservative, hook-forward tuning on top of these defaults.
    hook_safe_mode: bool = False

    # Dynamics safety: prevent "out of the blue" bar-to-bar loudness jumps by limiting
    # per-channel average velocity changes between adjacent bars.
    bar_velocity_jump_limit_enabled: bool = True
    bar_velocity_jump_limit_ratio: float = 1.0
    # Deterministic groove layer: scales structured velocity accents (downbeats / offbeats).
    # Lower = calmer, less "slammy" dynamics (helpful for dense/high-tempo emotions).
    groove_accent_strength: float = 0.75

    # Cinematic micro-timing: small deterministic timing offsets (seconds) for chords/arp.
    micro_timing_enabled: bool = True
    micro_timing_chords_max_ms: float = 18.0
    micro_timing_arp_max_ms: float = 14.0

    # Lead performance model (channel 2): deterministic microtiming + optional swing.
    melody_microtiming_enabled: bool = True
    melody_microtiming_max_ms: float = 10.0
    melody_swing_enabled: bool = False
    melody_swing_amount: float = 0.08  # 0..0.25 (delay every other 8th-note feel)

    # Lead articulation shaping by phrase role (applied post-generation, pre-humanize).
    melody_gate_mult_opening: float = 0.95
    melody_gate_mult_answer: float = 1.00
    melody_gate_mult_cadence: float = 1.08
    melody_vel_mult_opening: float = 0.96
    melody_vel_mult_answer: float = 1.00
    melody_vel_mult_cadence: float = 1.06
    # Lead phrase breathing: leave a small rest before phrase boundaries so the
    # melody reads more like a performed/sung line instead of continuous note-fill.
    melody_phrase_breath_enabled: bool = True
    melody_phrase_breath_beats: float = 0.16
    melody_phrase_breath_min_note_beats: float = 0.20
    # Final whole-song safety pass. This catches notes added by song-level polish after
    # section-local breathing has already run.
    whole_song_phrase_breath_enabled: bool = True
    whole_song_phrase_breath_beats: float = 0.18
    whole_song_phrase_breath_min_note_beats: float = 0.20
    # Final lead singability guard. Uses octave displacement only, preserving pitch class
    # while keeping the rendered melody in a performable range/leap envelope.
    whole_song_lead_singability_guard_enabled: bool = True
    whole_song_lead_target_range_semitones: int = 24
    whole_song_lead_max_leap_semitones: int = 14
    # Final chorus strength guard. Adds restrained lead accents when chorus lead
    # density falls below the verse enough to read as weaker.
    whole_song_chorus_strength_guard_enabled: bool = True
    whole_song_chorus_strength_min_ratio: float = 0.90
    # Final bass motion guard for non-intro/outro sections that otherwise repeat one
    # bass pitch for the entire section.
    whole_song_bass_motion_guard_enabled: bool = True
    # Final whole-song dynamics safety. This avoids bar-to-bar velocity jumps introduced
    # by postprocess additions/ducks after section-local dynamics limiting.
    whole_song_bar_velocity_smoothing_enabled: bool = True
    whole_song_bar_velocity_smoothing_ratio: float = 1.35
    whole_song_bar_velocity_smoothing_floor: int = 30
    # Final lead/arp masking guard. Runs after all arp-floor passes and ducks arp hits
    # that overlap active melody while preserving a minimum arp bed per bar.
    whole_song_lead_arp_overlap_guard_enabled: bool = True
    whole_song_lead_arp_overlap_min_arp_per_bar: int = 3
    whole_song_lead_arp_overlap_min_arp_per_bar_chorus: int = 5
    whole_song_lead_arp_overlap_velocity_duck: int = 14

    # Counter-melody (sparse, rule-based).
    counter_melody_enabled: bool = True
    # Counter layer mode:
    # - "counter": existing sparse answer-line behaviour
    # - "strings_harmony": sustained harmony-style support (still channel 5)
    counter_melody_mode: str = "counter"
    # Strings-harmony controls (used when counter_melody_mode == "strings_harmony").
    strings_harmony_enabled: bool = False
    strings_harmony_hold_beats: float = 3.5
    strings_harmony_velocity_scale: float = 0.92

    # ------------------------------------------------------------------
    # Debug output (realtime)
    # ------------------------------------------------------------------
    # If enabled, the realtime player logs a compact trace line per generated bar.
    debug_bar_trace_enabled: bool = False
    # If enabled, log a short harmony summary on each section switch.
    debug_section_summary_enabled: bool = False

    # Cadence-aware voice leading: bias final/cadence bars toward resolution.
    cadence_voice_leading_enabled: bool = True
    cadence_voice_leading_weight: float = 1.0

    # Voice-leading solver safety caps (important for offline dataset generation).
    # These caps prevent rare worst-case search blowups from stalling training runs.
    # Set to 0 to disable the cap.
    voice_leading_time_budget_s: float = 0.40
    # Optional override for `VoiceLeadingEngine.beam_width` (0 disables override).
    voice_leading_beam_width: int = 10
    # Cap how many candidate note-options we consider per part before combining.
    # This is applied inside the voice-leading engine (quality/speed tradeoff).
    voice_leading_max_part_options: int = 24

    # Learned-style phrase contour planner (replaces most heuristic overrides).
    learned_contour_planner_enabled: bool = True
    learned_contour_planner_strength: float = 0.75

    # Runtime masking constraints: enforce call/response by avoiding lead onsets
    # on top of dense arp/counter activity (at sampling time, not only in the scorer).
    masking_constraints_runtime_enabled: bool = True
    masking_constraints_strength: float = 0.70

    # Pitch-aware masking: when overlap is unavoidable, discourage lead landing on
    # the same pitch class as the arp bed at that onset step (0..1).
    masking_pc_avoid_strength: float = 0.55

    # Beat-grid helper for “strong beat” detection (in beats).
    strong_beat_epsilon_beats: float = 0.06

    # Arp↔melody compatibility scoring (used by live best-of-K section picker).
    arp_melody_compat_scoring_enabled: bool = True
    arp_melody_compat_weight: float = 0.25
    arp_melody_pc_collision_weight: float = 1.0
    arp_melody_strongbeat_mask_weight: float = 0.75
    arp_melody_register_sep_weight: float = 0.65
    # Desired minimum separation (arp under lead) when both are active.
    arp_melody_register_separation_semitones: int = 5
    # Melody↔harmony agreement scorer macro:
    # - "tight": strongest hook/cadence chord-tone pressure
    # - "balanced": default
    # - "loose": more permissive / expressive
    melody_harmony_agreement_preset: str = "balanced"

    # Optional post-pass: refine arp pitches against realized lead (keep rhythm fixed).
    arp_refine_against_lead_enabled: bool = True

    # Arp vs lead interaction:
    # When enabled, the arp may change its chord-tone selection to avoid the lead's active pitch
    # classes. This can sound "clever" but also makes arps feel non-standard/strange.
    # Default OFF so arps remain normal chord-tone patterns; use ducking/masking instead.
    arp_avoid_lead_pitch_classes_enabled: bool = False

    # Arp harmonic policy:
    # - when enabled, the arp cycles through *all* chord tones of the current progression chord
    #   (ordered by arp mode: up/down/etc), rather than selecting subsets or adding non-chord tones.
    arp_use_all_chord_tones_enabled: bool = True
    # If True, allow the arp to occasionally add "color" passing tones from the emotion scale.
    # Default OFF for a strict chord-tone arpeggiator.
    arp_non_chord_tones_enabled: bool = False

    # Bidirectional motif glue: softly align lead onsets to the hook motif rhythm grid.
    motif_melody_alignment_enabled: bool = True
    motif_melody_alignment_strength: float = 0.25

    # ------------------------------------------------------------------
    # Arp↔melody coupling controls (motif + groove)
    # ------------------------------------------------------------------
    # Shared PhraseIntent bus (Stage 1 big-upgrades roadmap).
    phrase_intent_bus_enabled: bool = False

    # Arp rhythm cell vocabulary (Stage 2 big-upgrades roadmap).
    arp_rhythm_cells_enabled: bool = False
    arp_rhythm_cells_strength: float = 0.75

    # Harmony-aware dialogue policy (Stage 3 big-upgrades roadmap).
    dialogue_harmony_policy_enabled: bool = False
    dialogue_harmony_policy_strength: float = 0.75

    # Joint generation loop (Stage 4 big-upgrades roadmap).
    joint_generation_enabled: bool = False
    # Phase C: when joint generation is on, lock harmony to joint plan chord symbols when none provided.
    joint_plan_lock_harmony: bool = True
    # Phase C+: snap chorus Markov degrees to joint ``hook_degrees`` (skip heavy blueprint melody overlay).
    joint_plan_markov_conditioning_enabled: bool = True
    joint_generation_max_iters: int = 3
    joint_generation_budget_ms: float = 120.0
    # Same determinism rationale as `section_pick_use_wall_clock`.
    joint_generation_use_wall_clock: bool = False

    # Motif system upgrades (Stage 5 big-upgrades roadmap).
    motif_multi_length_enabled: bool = False
    motif_rhythm_only_enabled: bool = False

    # Register choreography (Stage 6 big-upgrades roadmap).
    register_choreography_enabled: bool = False
    register_choreography_strength: float = 0.75
    # If true, allow the arpeggiator to derive its tone ordering from the
    # shared hook motif contour when available (instead of only fixed modes).
    arp_motif_coupling_enabled: bool = False
    # 0..1: how strongly motif-driven ordering should influence the arp.
    # 0 = disabled (fall back to normal modes), 1 = prefer motif-shaped cycles
    # in chorus/hook-style roles when a SongHookMotif is present.
    arp_motif_coupling_strength: float = 0.6
    # If True, allow the arp engine to introduce per-bar mode variety (up/down/etc).
    # Default ON so the arp doesn't feel like the same loop forever.
    arp_allow_mode_variation_enabled: bool = True
    # 0..1: how much the arp grid/density should try to follow the lead's
    # phrase rhythm templates vs using only emotion-driven defaults.
    arp_melody_groove_link_strength: float = 0.0
    # Groove-link mode for arp step selection when a melody onset grid is available.
    # - "mirror": align arp onsets with the melody template (groove lock)
    # - "complement": avoid melody onsets and fill gaps (call/response)
    arp_groove_link_mode: str = "complement"
    # High-level jam mode: how tightly to couple arp and melody layers.
    # - "loose": current behaviour (light masking + optional refinement only)
    # - "motif_locked": prefer motif-driven ordering when hooks are present
    # - "call_response_strong": favour post-pass arp refinement against lead
    #   and keep lead sparser over dense arps.
    arp_melody_coupling_mode: str = "loose"
    # 0..1: when >0, allow section planners to thin arp density slightly in
    # bars where the realized melody is very busy (call-and-response feel).
    arp_density_follow_melody: float = 0.35
    # Counterlines should answer the lead rather than competing with it.
    # Lower = gentler overlap thinning vs lead (counter stays louder when both sound together).
    counter_melody_follow_lead_strength: float = 0.36

    # Arp→melody motif feedback: extract motifs from arp patterns and add them
    # to the motif library so later melodies can quote the bed.
    arp_to_melody_motif_feedback_enabled: bool = False
    arp_to_melody_motif_feedback_prob: float = 0.35

    # Phrase rerank: include masking (occupied intervals) in phrase-level best-of-K scoring.
    melody_phrase_rerank_masking_weight: float = 0.25

    # Optional: expose a per-grid masking map into rhythm selection.
    masking_grid_enabled: bool = False
    masking_grid_strength: float = 0.7

    # Jam-friendly macro: 0..1 overall arp–melody dialogue strength.
    dialogue_amount: float = 0.0
    # Optional coarse preset ladder for live control.
    # "off"|"tight"|"strong"|"experimental" (empty = ignore)
    dialogue_preset: str = ""

    # ------------------------------------------------------------------
    # Markov + compositional upgrades (staged, feature-flagged)
    # ------------------------------------------------------------------
    # When True, apply_melody_staged_experimental_bundle() enables coupling,
    # joint rhythm–pitch rerank, and breath biases (see function below).
    melody_staged_experimental_bundle_enabled: bool = True
    melody_position_conditioning_enabled: bool = True
    melody_position_conditioning_strength: float = 0.75
    melody_rhythm_pitch_coupling_enabled: bool = True
    melody_rhythm_pitch_coupling_strength: float = 0.65
    # After a short note, bias intervals toward stepwise motion; after a long
    # held note, allow slightly wider leaps (complements rhythm→pitch coupling).
    melody_interval_duration_coupling_enabled: bool = True
    melody_interval_duration_coupling_strength: float = 0.65
    melody_voiceleading_rerank_enabled: bool = True
    melody_voiceleading_rerank_strength: float = 0.60
    # Scale rest insertion probability by section breath_window (high breath → more space).
    melody_breath_rest_bias_enabled: bool = False
    melody_breath_rest_bias_strength: float = 0.65
    # At rhythm sample time: high breath_window[bar] → sparser onsets (longer IOIs).
    melody_breath_rhythm_bias_enabled: bool = False
    melody_breath_rhythm_bias_strength: float = 0.65

    # Training: do not compute interval deltas across rests (degree < 0).
    melody_train_rest_safe_intervals_enabled: bool = True
    # Generation: allow (-1, dur) rest tokens in the Markov phrase stream (staged).
    melody_generation_rest_tokens_enabled: bool = True
    melody_rest_token_step_probability: float = 0.03

    # Reweight duration probs using interval Markov marginal (joint-ish, cheap).
    melody_joint_rhythm_pitch_rerank_enabled: bool = False
    melody_joint_rhythm_pitch_rerank_strength: float = 0.55
    # Top-K duration candidates before joint reweighting (0 = use full support).
    melody_joint_rhythm_pitch_rerank_k: int = 0
    # Stage-2 refactor toggle: when enabled, `_select_rhythm` samples directly
    # from `_rhythm_distribution` (single-pass conditioning).
    melody_rhythm_single_pass_enabled: bool = False

    # ------------------------------------------------------------------
    # Stage 3: unify phrase "repair stack" into a single objective
    # ------------------------------------------------------------------
    # When True, phrase candidate scoring includes additional "repair intent"
    # terms (static-run avoidance, contour tilt, long-breath preference).
    melody_phrase_objective_enabled: bool = False
    # When False, skip the post-hoc phrase repair stack and rely on the
    # phrase objective + best-of-K selection instead.
    melody_phrase_repair_stack_enabled: bool = True
    # Objective weights (kept modest; this is a rerank layer, not hard rules).
    melody_phrase_objective_static_run_weight: float = 0.22
    melody_phrase_objective_contour_weight: float = 0.16
    melody_phrase_objective_long_breath_weight: float = 0.12

    # Phase 2a: trained P(next_interval | duration bucket of preceding voiced note).
    melody_interval_prev_duration_markov_enabled: bool = False
    melody_interval_prev_duration_markov_blend: float = 0.35

    # Phase 2b: rhythm Markov uses signed durations — positive = voiced note length,
    # negative = rest of abs(length). Train from data; generation uses rhythm-first order.
    melody_rest_rhythm_tokens_train_enabled: bool = False
    melody_rest_rhythm_tokens_generate_enabled: bool = False

    # Phase 2c: hierarchical phrase-gesture interval Markov (opening / middle / cadence).
    melody_train_gesture_interval_models: bool = False
    melody_gesture_interval_markov_enabled: bool = False
    melody_gesture_interval_markov_blend: float = 0.28

    # Phase 2d: linear logit residual on interval logits (numpy weights; Markov stays prior).
    melody_neural_logit_residual_enabled: bool = False
    melody_neural_logit_residual_strength: float = 0.35
    melody_neural_logit_residual_path: str = ""
    melody_neural_logit_residual_order: int = 6

    # Phase 2e: JSONL batch retrain / eval (see scripts/melody_jsonl_retrain.py, melody_eval_gate.py).
    melody_jsonl_retrain_min_notes: int = 4
    melody_jsonl_retrain_min_accept_score: float = 0.0
    melody_jsonl_eval_max_rest_rate: float = 0.55
    melody_jsonl_eval_min_mean_accept: float = 0.0
    melody_jsonl_eval_min_lines: int = 1
    melody_jsonl_eval_min_emotions: int = 0
    melody_jsonl_eval_min_section_roles: int = 0
    melody_jsonl_eval_max_emotion_share: float = 1.0
    melody_jsonl_eval_min_mean_lyrical: float = 0.0

    # ------------------------------------------------------------------
    # Hook / motif development (realtime-safe)
    # ------------------------------------------------------------------
    # 0..1: strength of role-conditioned motif transform policy in Markov motif application.
    # 0 keeps legacy uniform random variation choice; 1 uses role+development-weighted choice.
    hook_transform_strength: float = 0.55
    # If true, allow MotifPlanManager to use the contrast motif for bridge-like roles (a_prime).
    hook_contrast_answer_enabled: bool = True
    # 0..1: section-level hook evolution speed (statement -> variation -> fragment).
    hook_development: float = 0.42
    # 0..1: probability of anchoring injected hook motifs to PhrasePlanner's hook_anchor_degree
    # when available (higher = more stable, recognizable restatements).
    hook_anchor_degree_strength: float = 0.93
    # Dedicated chorus-hook composer: stabilize chorus phrase shapes and restate the
    # opening phrase into later phrases so hooks feel more intentional.
    # Phase 1 (expressive chorus lead): default lowered so phrase contours stay less
    # "same arch, smoothed note counts" under heavy Markov+rerank.
    chorus_hook_composer_enabled: bool = True
    chorus_hook_composer_strength: float = 0.78
    # 0..1: phrase-level chorus singability scorer used during best-of-K reranking.
    # (Rewards small pitch set, stepwise, symmetry; high values can feel generic.)
    chorus_topline_scorer_enabled: bool = True
    chorus_topline_scorer_strength: float = 0.48
    # Post-generation vocal phrase grammar: held cadences, phrase-answer spacing,
    # and small pickup repairs for sparse but non-intro sections.
    phrase_vocal_grammar_enabled: bool = True
    phrase_vocal_grammar_strength: float = 0.68
    # Conservative musical QA/repair pass after generation. Repairs only clear
    # failures: empty lead bars in core song sections, weak bass support, and
    # missing final-bar handoff hints.
    post_generation_qa_enabled: bool = True
    post_generation_qa_strength: float = 0.58
    # Chorus/hook identity QA: if the hook section opens with an idea but the
    # following bar does not answer/restate it, copy a restrained restatement.
    hook_strength_qa_enabled: bool = True
    hook_strength_qa_strength: float = 0.62
    # Final layer cleanup: thin arp/counter clutter when it masks a busy lead.
    arrangement_collision_manager_enabled: bool = True
    arrangement_collision_manager_strength: float = 0.62
    # Role contrast QA: keep verses slightly open and make chorus downbeats read.
    section_contrast_qa_enabled: bool = True
    section_contrast_qa_strength: float = 0.55
    # 0..1: write small end-of-section lead pickups into the next section target.
    transition_pickup_writer_enabled: bool = True
    transition_pickup_writer_strength: float = 0.72
    # 0..1: final-chorus/tag/outro payoff shaping across timeline targets + arrangement curves.
    final_chorus_payoff_enabled: bool = True
    final_chorus_payoff_strength: float = 0.72
    # 0..1: shape section endings based on the upcoming role so transitions feel
    # authored rather than only globally smoothed.
    transition_composer_strength: float = 0.78
    transition_composer_enabled: bool = True
    # Audible end-of-section arrangement gestures: bass pickups, chord anticipations,
    # arp lift fills, and release thinning driven by the next section role.
    transition_arrangement_gestures_enabled: bool = True
    transition_arrangement_gestures_strength: float = 0.72
    # Full-song melodic continuity pass: after sections are stitched together,
    # write small lead pickups into important next-section openings.
    whole_song_melodic_pickups_enabled: bool = True
    whole_song_melodic_pickups_strength: float = 0.72
    # Full-song thematic reprise pass: restate short hook/verse motifs in later
    # chorus, tag, and developed-return sections.
    whole_song_melody_reprise_enabled: bool = True
    whole_song_melody_reprise_strength: float = 0.78
    # Whole-song theme development: derive a hook cell and rewrite intro/verse/pre/chorus
    # with recognisable but non-copy-paste variants (targets motif_development_score).
    whole_song_theme_development_enabled: bool = True
    whole_song_theme_development_strength: float = 0.82
    whole_song_hook_identity_reinforce_enabled: bool = True
    whole_song_hook_identity_strength: float = 0.85
    # Final whole-song producer/director pass: role register shaping, dynamic
    # automation, repeated-section lift, hook fragments, and sparse-role thinning.
    whole_song_professionalizer_enabled: bool = True
    whole_song_professionalizer_strength: float = 0.70
    # Timeline shaping toggles (kept explicit for quality tuning + presets).
    timeline_role_contrast_enabled: bool = True
    # 0..1: additional chart-style verse/chorus/pre-chorus multipliers (after
    # `timeline_role_contrast_*`). 0.0 = off (default for stable regression tests).
    pop_arrangement_strength: float = 0.0
    # 0..1: best-of-K `score_section` bonus for hook-like lead openings (chorus-like
    # roles) when the first two bars show concentrated pitch use. 0.0 = off.
    pop_hook_scoring_strength: float = 0.0
    timeline_phrase_targets_enabled: bool = True
    # 0..1: section-role orchestration script for staged layer entry/exit,
    # arp spotlighting, and controlled post-chorus release.
    orchestration_script_strength: float = 0.8
    orchestration_script_enabled: bool = True
    # 0..1: role-aware bass motif families with section-to-section reuse.
    bass_motif_system_strength: float = 0.72
    bass_motif_system_enabled: bool = True
    # 0..1: smarter bass line adaptation (stepwise motion + cadence-aware anchoring).
    bass_intelligence_enabled: bool = True
    bass_intelligence_strength: float = 0.72
    # 0..1: emotion-specific bass grammar layered on top of section roles.
    emotion_bass_personality_enabled: bool = True
    emotion_bass_personality_strength: float = 0.65
    # Optional timeline target lane for future drum/percussion generation.
    percussion_lane_enabled: bool = True
    # 0..1: role-aware counterline entry/response scripting.
    countermelody_script_strength: float = 0.72
    countermelody_script_enabled: bool = True
    # 0..1: keep motif behavior grouped into reusable families across sections.
    motif_family_tracking_enabled: bool = True
    motif_family_tracking_strength: float = 0.75
    # Optional self-evaluation feedback loop that gently retunes composition knobs.
    self_eval_autotune_enabled: bool = True
    self_eval_autotune_strength: float = 0.35
    self_eval_autotune_window: int = 4

    # ------------------------------------------------------------------
    # Data audit / normalization (guardrails against "aggressive" datasets)
    # ------------------------------------------------------------------
    data_audit_enabled: bool = True
    data_normalize_enabled: bool = True
    # Clamp core scalars (applied when normalizing emotion-driven curves/pools).
    data_clamp_tempo_mult_min: float = 0.55
    data_clamp_tempo_mult_max: float = 1.55
    data_clamp_density_min: float = 0.15
    data_clamp_density_max: float = 1.00
    # Arrangement curve clamps (post-merge, before use).
    data_curve_clamp_chord_motion_min: float = 0.70
    data_curve_clamp_chord_motion_max: float = 1.45
    data_curve_clamp_chord_rhythm_min: float = 0.75
    data_curve_clamp_chord_rhythm_max: float = 1.35
    data_curve_clamp_melody_density_min: float = 0.45
    data_curve_clamp_melody_density_max: float = 1.55
    data_curve_clamp_arp_density_min: float = 0.0
    data_curve_clamp_arp_density_max: float = 1.65
    data_curve_clamp_section_dynamic_min: float = 0.85
    data_curve_clamp_section_dynamic_max: float = 1.12
    # Cached bundle of MelodyRoleDensity / HarmonyTension / MelodyPhrasePlanning / RealtimeForm views.
    _group_profile_cache: Optional[CompositionRuntimeProfile] = field(
        default=None, init=False, repr=False, compare=False
    )

    def __setattr__(self, name: str, value: object) -> None:
        object.__setattr__(self, name, value)
        if name != "_group_profile_cache":
            object.__setattr__(self, "_group_profile_cache", None)

    def _get_runtime_profile(self) -> CompositionRuntimeProfile:
        cached = self._group_profile_cache
        if cached is not None:
            return cached
        profile = build_composition_runtime_profile(self)
        object.__setattr__(self, "_group_profile_cache", profile)
        return profile

    def warm_runtime_profile_cache(self) -> None:
        """Materialize and cache grouped views once (call after CONFIG.composition is fully settled)."""
        self._get_runtime_profile()

    @property
    def runtime_profile(self) -> CompositionRuntimeProfile:
        """Frozen snapshot of all logical group views; invalidated when any composition field is assigned."""
        return self._get_runtime_profile()

    @property
    def melody_role_density(self) -> "MelodyRoleDensityGroup":
        return self._get_runtime_profile().melody_role_density

    @property
    def harmony_tension(self) -> "HarmonyTensionControlGroup":
        return self._get_runtime_profile().harmony_tension

    @property
    def melody_phrase_planning(self) -> "MelodyPhrasePlanningGroup":
        return self._get_runtime_profile().melody_phrase_planning

    @property
    def realtime_form(self) -> "RealtimeFormGroup":
        return self._get_runtime_profile().realtime_form


def apply_melody_staged_experimental_bundle(comp: CompositionConfiguration) -> None:
    """Turn on staged Markov melody experiments (coupling, joint rerank, breath)."""
    if not getattr(comp, "melody_staged_experimental_bundle_enabled", False):
        return
    comp.melody_rhythm_pitch_coupling_enabled = True
    comp.melody_interval_duration_coupling_enabled = True
    comp.melody_joint_rhythm_pitch_rerank_enabled = True
    if int(getattr(comp, "melody_joint_rhythm_pitch_rerank_k", 0) or 0) <= 0:
        comp.melody_joint_rhythm_pitch_rerank_k = 8
    comp.melody_breath_rest_bias_enabled = True
    comp.melody_breath_rhythm_bias_enabled = True
