"""Tests for scripts/generate_dependency_manifest.py's lock-file parser.

Regression coverage for a real bug caught while building this: the first
version's pin regex only matched plain `name==version` lines. Regenerating
the lock files with `--generate-hashes` (required for the release
checklist's "hash-locked dependency artifacts" item) changes every pin line
to `name==version \\` with hash continuation lines below it -- the original
regex silently matched zero packages against the hash-locked format.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import generate_dependency_manifest as gdm  # noqa: E402


def test_parses_plain_pins_without_hashes(tmp_path):
    lock = tmp_path / "requirements.lock.txt"
    lock.write_text(
        "#\n# autogenerated\n#\nanyio==4.14.2\n"
        "    # via httpx\n"
        "attrs==26.1.0\n"
        "    # via jsonschema\n",
        encoding="utf-8",
    )
    pins = gdm._parse_lock_file(lock)
    assert pins == {"anyio": "4.14.2", "attrs": "26.1.0"}


def test_parses_hash_locked_pins():
    """The actual --generate-hashes format: trailing backslash + indented
    --hash lines, which the original (fixed) regex failed to match."""
    lock_text = (
        "#\n# autogenerated\n#\n"
        "anyio==4.14.2 \\\n"
        "    --hash=sha256:aaaa \\\n"
        "    --hash=sha256:bbbb\n"
        "    # via httpx\n"
        "attrs==26.1.0 \\\n"
        "    --hash=sha256:cccc\n"
        "    # via jsonschema\n"
    )
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        lock = Path(td) / "requirements.lock.txt"
        lock.write_text(lock_text, encoding="utf-8")
        pins = gdm._parse_lock_file(lock)
    assert pins == {"anyio": "4.14.2", "attrs": "26.1.0"}


def test_hash_lines_and_via_comments_are_not_mistaken_for_pins():
    import tempfile

    lock_text = (
        "anyio==4.14.2 \\\n"
        "    --hash=sha256:aaaa\n"
        "    # via httpx\n"
    )
    with tempfile.TemporaryDirectory() as td:
        lock = Path(td) / "requirements.lock.txt"
        lock.write_text(lock_text, encoding="utf-8")
        pins = gdm._parse_lock_file(lock)
    assert pins == {"anyio": "4.14.2"}


def test_missing_lock_file_returns_empty_dict(tmp_path):
    assert gdm._parse_lock_file(tmp_path / "does_not_exist.lock.txt") == {}


def test_license_info_for_a_real_installed_package_with_short_classifier():
    info = gdm._license_info("numpy")
    assert info["status"] == "ok"
    assert "BSD" in info["license"]


def test_license_info_for_a_package_not_installed():
    info = gdm._license_info("this-package-definitely-does-not-exist-xyz")
    assert info["status"] == "not_installed"


def test_build_manifest_deduplicates_and_flags_version_conflicts(tmp_path, monkeypatch):
    monkeypatch.setattr(gdm, "ROOT", tmp_path)
    monkeypatch.setattr(
        gdm,
        "LOCK_FILES",
        ["a.lock.txt", "b.lock.txt"],
    )
    (tmp_path / "a.lock.txt").write_text("numpy==2.0.0\n", encoding="utf-8")
    (tmp_path / "b.lock.txt").write_text("numpy==2.1.0\n", encoding="utf-8")

    manifest = gdm.build_manifest()
    conflict = next(e for e in manifest["packages"] if e["status"] == "version_conflict")
    assert conflict["package"] == "numpy"
