import Foundation

runSanitizerTests()
runTemplateTests()
runDetectorTests()
runFileOperationTests()
runPresetTests()
runArchiveTests()
runMediaExtractorTests()
runAudioArchiveRoundTripTests()
runPDFOptimizerTests()
runPDFExtractorTests()
runFolderCleanerTests()
runBatchSafetyTests()
runLicenseEngineTests()
runUpdateEngineTests()
runCorpusAndFailureTests()
finish()
