from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from time import monotonic
from urllib.parse import urlparse
from uuid import uuid4

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

from . import admin, auth, commerce, downloads, licensing
from .config import settings
from .database import engine
from .storage import StorageError, get_storage

# uvicorn attaches handlers to its own "uvicorn" logger tree, not the root
# logger, so INFO messages from our "nitedsp" logger would otherwise never
# reach any handler even with propagate=True (no handler == no output,
# regardless of level). Attach our own handler directly.
_nitedsp_logger = logging.getLogger("nitedsp")
_nitedsp_logger.setLevel(logging.INFO)


class _JsonFormatter(logging.Formatter):
    """Emit a safe structured envelope without copying exception text."""

    def format(self, record: logging.LogRecord) -> str:
        payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        if record.exc_info:
            payload["exception_type"] = record.exc_info[0].__name__
        return json.dumps(payload, sort_keys=True)


if not _nitedsp_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(_JsonFormatter())
    _nitedsp_logger.addHandler(_handler)
    _nitedsp_logger.propagate = False

def _allowed_cors_origins() -> list[str]:
    """The website is a separate origin from the API (Section 6) --
    credentialed cross-origin requests need an explicit allow-list, never
    a wildcard, since we allow_credentials. Phase 5.6, Section 16: also
    allow the "www." variant of an apex domain automatically, since a real
    site commonly gets visited both ways, without needing a second setting
    -- "do not allow wildcard authenticated CORS" is satisfied by this
    still being a short, explicit, derived list, not a pattern match.
    """
    origins = [settings.nite_dsp_public_url]
    parsed = urlparse(settings.nite_dsp_public_url)
    if parsed.hostname and not parsed.hostname.startswith("www."):
        www_netloc = f"www.{parsed.netloc}"
        origins.append(f"{parsed.scheme}://{www_netloc}")
    return origins


app = FastAPI(title="NITE DSP Backend", version="0.1.0")


@app.middleware("http")
async def observability_middleware(request: Request, call_next):
    """Attach a server-generated correlation ID without logging user content.

    The ID is deliberately generated by the service rather than accepting a
    caller-supplied value. Logs contain method, status, ID, and duration only;
    paths, query strings, bodies, addresses, and tokens stay out of the log.
    """
    request_id = uuid4().hex
    started = monotonic()
    try:
        response = await call_next(request)
    except Exception:
        _nitedsp_logger.exception(
            "request request_id=%s method=%s status=500 duration_ms=%d",
            request_id,
            request.method,
            round((monotonic() - started) * 1000),
        )
        raise
    response.headers["X-Request-ID"] = request_id
    _nitedsp_logger.info(
        "request request_id=%s method=%s status=%s duration_ms=%d",
        request_id,
        request.method,
        response.status_code,
        round((monotonic() - started) * 1000),
    )
    return response

app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_cors_origins(),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(licensing.router)
app.include_router(commerce.router)
app.include_router(commerce.checkout_router)
app.include_router(downloads.router)
app.include_router(admin.router)


@app.get("/health")
def health() -> dict:
    """Liveness only -- confirms the process is up and serving requests.
    Never checks dependencies (that's /ready's job) so a slow/degraded
    database doesn't make an otherwise-healthy process look dead."""
    return {"status": "ok", "environment": settings.environment}


@app.get("/ready")
def ready(response: Response) -> dict:
    """Readiness -- confirms critical dependencies are reachable, not just
    that the process started.
    Returns 503 rather than raising, so a load balancer's readiness probe
    gets a clean signal instead of a stack trace. Never includes secrets or
    connection strings in the response."""
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        db_ok = True
    except Exception:
        db_ok = False

    try:
        get_storage().readiness()
        storage_ok = True
    except (StorageError, OSError):
        storage_ok = False

    email_provider_configured = settings.email_provider in ("console", "resend") and (
        settings.email_provider == "console" or bool(settings.resend_api_key)
    )
    storage_durable = settings.storage_backend == "s3"
    email_deliverable = settings.email_provider == "resend" and bool(settings.resend_api_key)
    customer_rehearsal_ready = (
        not settings.staging_customer_rehearsal
        or (storage_durable and email_deliverable)
    )
    ready_ok = db_ok and storage_ok and customer_rehearsal_ready
    if not ready_ok:
        response.status_code = 503
    return {
        "status": "ok" if ready_ok else "unavailable",
        "database": db_ok,
        "storage": storage_ok,
        "storage_backend": settings.storage_backend,
        "storage_durable": storage_durable,
        "email_provider": settings.email_provider,
        "email_provider_configured": email_provider_configured,
        "email_deliverable": email_deliverable,
        "checkout_enabled": settings.paddle_checkout_enabled,
        "staging_customer_rehearsal": settings.staging_customer_rehearsal,
        "staging_customer_rehearsal_ready": customer_rehearsal_ready,
    }
