"""add entitlement license_key

Revision ID: 34e889215e56
Revises: 28f667ac6547
Create Date: 2026-08-13 01:01:39.348473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e889215e56'
down_revision: Union[str, Sequence[str], None] = '28f667ac6547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('entitlements', sa.Column('license_key', sa.String(), nullable=False))
    # Named explicitly -- Alembic's autogenerated `None` name let Postgres
    # pick its own default ("entitlements_license_key_key"), which made the
    # downgrade below impossible to express (Alembic can't drop a
    # constraint it was never told the name of). Found via a migration
    # rehearsal (Phase 5, Section 58) before any real customer data existed.
    op.create_unique_constraint('entitlements_license_key_key', 'entitlements', ['license_key'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('entitlements_license_key_key', 'entitlements', type_='unique')
    op.drop_column('entitlements', 'license_key')
